//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class Screen1 : Neo.ApplicationFramework.Controls.Controls.Form {
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button1;
        
        private Neo.ApplicationFramework.Controls.Controls.SliderCF m_Slider;
        
        private Neo.ApplicationFramework.Controls.Controls.LinearMeterCF m_LinearMeter;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric1;
        
        private Neo.ApplicationFramework.Controls.Symbol.SymbolCF m_MultiPicture20;
        
        private Neo.ApplicationFramework.Controls.Symbol.SymbolCF m_MultiPicture;
        
        private bool m_Initialized_Screen1;
        
        public Screen1() {
            this.InitializeComponent();
            this.Button.Click += new System.EventHandler(this.Button_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LinearMeterBaseCFAdapter Slider {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LinearMeterBaseCFAdapter>(this.m_Slider);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LinearMeterBaseCFAdapter LinearMeter {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LinearMeterBaseCFAdapter>(this.m_LinearMeter);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter MultiPicture20 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_MultiPicture20);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter MultiPicture {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_MultiPicture);
            }
        }
        
        private void InitializeComponent() {
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem1 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem2 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem3 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem4 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval5 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem5 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval6 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem6 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval7 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem7 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval8 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem8 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval9 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem9 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval10 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem10 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval11 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem11 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval12 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem12 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval13 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem13 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval14 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem14 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval15 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem15 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval16 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem16 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            this.m_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button1 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Slider = new Neo.ApplicationFramework.Controls.Controls.SliderCF();
            this.m_LinearMeter = new Neo.ApplicationFramework.Controls.Controls.LinearMeterCF();
            this.m_AnalogNumeric = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_AnalogNumeric1 = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_MultiPicture20 = new Neo.ApplicationFramework.Controls.Symbol.SymbolCF();
            this.m_MultiPicture = new Neo.ApplicationFramework.Controls.Symbol.SymbolCF();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Slider)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_LinearMeter)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture20)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture)).BeginInit();
            this.SuspendLayout();
            // 
            // Screen1
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.SingleBorder;
            this.ControlBox = false;
            // 
            // m_Button
            // 
            this.m_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_Button.BlinkDynamicsValue = false;
            this.m_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button.EnabledDynamicsValue = true;
            this.m_Button.FontSizePixels = 15;
            this.m_Button.ForceTransparency = true;
            this.m_Button.Height = 100;
            this.m_Button.IndicatorMargin = null;
            this.m_Button.Left = 33;
            this.m_Button.Name = "m_Button";
            this.m_Button.RequiresTransparency = true;
            this.m_Button.ScreenOwnerName = "Screen1";
            this.m_Button.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_Button.TextHeight = 18;
            this.m_Button.TextValue = 0D;
            this.m_Button.TextWidth = 160;
            this.m_Button.Top = 390;
            this.m_Button.Value = 0D;
            this.m_Button.VisibleDynamicsValue = true;
            this.m_Button.VisualPropertiesHashCode = -2051891566;
            this.m_Button.Width = 170;
            // 
            // m_Button1
            // 
            this.m_Button1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_Button1.BlinkDynamicsValue = false;
            this.m_Button1.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button1.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button1.EnabledDynamicsValue = true;
            this.m_Button1.FontSizePixels = 15;
            this.m_Button1.ForceTransparency = true;
            this.m_Button1.Height = 100;
            this.m_Button1.IndicatorMargin = null;
            this.m_Button1.Left = 224;
            this.m_Button1.Name = "m_Button1";
            this.m_Button1.RequiresTransparency = true;
            this.m_Button1.ScreenOwnerName = "Screen1";
            this.m_Button1.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_Button1.TextHeight = 18;
            this.m_Button1.TextValue = 0D;
            this.m_Button1.TextWidth = 160;
            this.m_Button1.Top = 390;
            this.m_Button1.Value = 0D;
            this.m_Button1.VisibleDynamicsValue = true;
            this.m_Button1.VisualPropertiesHashCode = -2051891566;
            this.m_Button1.Width = 170;
            // 
            // m_Slider
            // 
            this.m_Slider.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Slider.BlinkDynamicsValue = false;
            this.m_Slider.EnabledDynamicsValue = true;
            this.m_Slider.Focus = false;
            this.m_Slider.FontSizePixels = 12;
            this.m_Slider.ForceTransparency = false;
            this.m_Slider.Foreground = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Slider.Height = 385;
            this.m_Slider.IndicatorColor = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(190)))), ((int)(((byte)(212)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Slider.IndicatorMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(23D, 43.099999999999966D, 32.650000000000006D, 43.485000000000014D);
            this.m_Slider.InvalidateAtValueChanged = true;
            this.m_Slider.Left = 696;
            this.m_Slider.MajorScaleMarginFirst = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(12D, 43.099999999999966D, 56.125D, 43.485000000000014D);
            this.m_Slider.MajorScaleMarginSecond = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(double.NaN, double.NaN, double.NaN, double.NaN);
            this.m_Slider.MajorTickCount = 11;
            this.m_Slider.Maximum = 100D;
            this.m_Slider.Minimum = 0D;
            this.m_Slider.MinorScaleMarginFirst = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(15.75D, 43.099999999999966D, 59.875D, 43.485000000000014D);
            this.m_Slider.MinorScaleMarginSecond = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(double.NaN, double.NaN, double.NaN, double.NaN);
            this.m_Slider.MinorTickCount = 1;
            this.m_Slider.Name = "m_Slider";
            this.m_Slider.Orientation = Neo.ApplicationFramework.Controls.Controls.OrientationCF.Vertical;
            this.m_Slider.RequiresTransparency = false;
            this.m_Slider.ScaleColor = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Slider.ScreenOwnerName = "Screen1";
            this.m_Slider.TextScaleMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(46.474999999999994D, 43.099999999999966D, 12D, 43.485000000000014D);
            this.m_Slider.Top = 123;
            this.m_Slider.VisibleDynamicsValue = true;
            this.m_Slider.Width = 78;
            // 
            // m_LinearMeter
            // 
            this.m_LinearMeter.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(129)))), ((int)(((byte)(189))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_LinearMeter.BlinkDynamicsValue = false;
            this.m_LinearMeter.EnabledDynamicsValue = true;
            this.m_LinearMeter.FontSizePixels = 12;
            this.m_LinearMeter.ForceTransparency = false;
            this.m_LinearMeter.Foreground = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_LinearMeter.Height = 345;
            this.m_LinearMeter.IndicatorColor = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(28)))), ((int)(((byte)(61)))), ((int)(((byte)(222))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_LinearMeter.IndicatorMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(8D, 14D, 31.650000000000006D, 14D);
            this.m_LinearMeter.InvalidateAtValueChanged = true;
            this.m_LinearMeter.Left = 453;
            this.m_LinearMeter.MajorScaleMarginFirst = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(173.35D, 14D, 24.650000000000006D, 14D);
            this.m_LinearMeter.MajorScaleMarginSecond = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(double.NaN, double.NaN, double.NaN, double.NaN);
            this.m_LinearMeter.MajorTickCount = 6;
            this.m_LinearMeter.Maximum = 100D;
            this.m_LinearMeter.Minimum = 0D;
            this.m_LinearMeter.MinorScaleMarginFirst = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(173.35D, 14D, 26.650000000000006D, 14D);
            this.m_LinearMeter.MinorScaleMarginSecond = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(double.NaN, double.NaN, double.NaN, double.NaN);
            this.m_LinearMeter.MinorTickCount = 1;
            this.m_LinearMeter.Name = "m_LinearMeter";
            this.m_LinearMeter.Orientation = Neo.ApplicationFramework.Controls.Controls.OrientationCF.Vertical;
            this.m_LinearMeter.RequiresTransparency = false;
            this.m_LinearMeter.ScaleColor = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_LinearMeter.ScreenOwnerName = "Screen1";
            this.m_LinearMeter.TextScaleMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(181.35D, 14D, 5D, 14D);
            this.m_LinearMeter.Top = 143;
            this.m_LinearMeter.VisibleDynamicsValue = true;
            this.m_LinearMeter.Width = 206;
            // 
            // m_AnalogNumeric
            // 
            this.m_AnalogNumeric.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_AnalogNumeric.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_AnalogNumeric.BlinkDynamicsValue = false;
            this.m_AnalogNumeric.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_AnalogNumeric.EnabledDynamicsValue = true;
            this.m_AnalogNumeric.FontSizePixels = 20;
            this.m_AnalogNumeric.Height = 44;
            this.m_AnalogNumeric.Left = 706;
            this.m_AnalogNumeric.Name = "m_AnalogNumeric";
            this.m_AnalogNumeric.ScreenOwnerName = "Screen1";
            this.m_AnalogNumeric.Top = 517;
            this.m_AnalogNumeric.VisibleDynamicsValue = true;
            this.m_AnalogNumeric.Width = 55;
            // 
            // m_AnalogNumeric1
            // 
            this.m_AnalogNumeric1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_AnalogNumeric1.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_AnalogNumeric1.BlinkDynamicsValue = false;
            this.m_AnalogNumeric1.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric1.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_AnalogNumeric1.EnabledDynamicsValue = true;
            this.m_AnalogNumeric1.FontSizePixels = 20;
            this.m_AnalogNumeric1.Height = 44;
            this.m_AnalogNumeric1.Left = 527;
            this.m_AnalogNumeric1.Name = "m_AnalogNumeric1";
            this.m_AnalogNumeric1.ScreenOwnerName = "Screen1";
            this.m_AnalogNumeric1.Top = 502;
            this.m_AnalogNumeric1.VisibleDynamicsValue = true;
            this.m_AnalogNumeric1.Width = 55;
            // 
            // m_MultiPicture20
            // 
            this.m_MultiPicture20.BlinkDynamicsValue = false;
            this.m_MultiPicture20.EnabledDynamicsValue = true;
            this.m_MultiPicture20.Height = 100;
            this.m_MultiPicture20.Left = 70;
            this.m_MultiPicture20.Name = "m_MultiPicture20";
            this.m_MultiPicture20.ScreenOwnerName = "Screen1";
            multisymbolitem1.SymbolName = "button green";
            multisymbolitem1.Transparent = false;
            symbolinterval1.Value = multisymbolitem1;
            symbolinterval2.End = 1D;
            symbolinterval2.Start = 1D;
            multisymbolitem2.SymbolName = "button black";
            multisymbolitem2.Transparent = false;
            symbolinterval2.Value = multisymbolitem2;
            symbolinterval3.End = 2D;
            symbolinterval3.Start = 2D;
            multisymbolitem3.SymbolName = "button yellow";
            multisymbolitem3.Transparent = false;
            symbolinterval3.Value = multisymbolitem3;
            symbolinterval4.End = 5D;
            symbolinterval4.Start = 3D;
            multisymbolitem4.SymbolName = "button orange";
            multisymbolitem4.Transparent = false;
            symbolinterval4.Value = multisymbolitem4;
            symbolinterval5.End = 5D;
            symbolinterval5.Start = 5D;
            multisymbolitem5.SymbolName = "button blue";
            multisymbolitem5.Transparent = false;
            symbolinterval5.Value = multisymbolitem5;
            symbolinterval6.End = 5D;
            symbolinterval6.Start = 5D;
            multisymbolitem6.SymbolName = "button red";
            multisymbolitem6.Transparent = false;
            symbolinterval6.Value = multisymbolitem6;
            symbolinterval7.End = 6D;
            symbolinterval7.Start = 6D;
            multisymbolitem7.SymbolName = "button purple";
            multisymbolitem7.Transparent = false;
            symbolinterval7.Value = multisymbolitem7;
            symbolinterval8.End = 7D;
            symbolinterval8.Start = 7D;
            multisymbolitem8.SymbolName = "button gray";
            multisymbolitem8.Transparent = false;
            symbolinterval8.Value = multisymbolitem8;
            symbolintervalmapper3.Intervals.Add(symbolinterval1);
            symbolintervalmapper3.Intervals.Add(symbolinterval2);
            symbolintervalmapper3.Intervals.Add(symbolinterval3);
            symbolintervalmapper3.Intervals.Add(symbolinterval4);
            symbolintervalmapper3.Intervals.Add(symbolinterval5);
            symbolintervalmapper3.Intervals.Add(symbolinterval6);
            symbolintervalmapper3.Intervals.Add(symbolinterval7);
            symbolintervalmapper3.Intervals.Add(symbolinterval8);
            this.m_MultiPicture20.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_MultiPicture20.SymbolName = "button green";
            this.m_MultiPicture20.Top = 143;
            this.m_MultiPicture20.Value = 0D;
            this.m_MultiPicture20.VisibleDynamicsValue = true;
            this.m_MultiPicture20.Width = 100;
            // 
            // m_MultiPicture
            // 
            this.m_MultiPicture.BlinkDynamicsValue = false;
            this.m_MultiPicture.EnabledDynamicsValue = true;
            this.m_MultiPicture.Height = 100;
            this.m_MultiPicture.Left = 274;
            this.m_MultiPicture.Name = "m_MultiPicture";
            this.m_MultiPicture.ScreenOwnerName = "Screen1";
            multisymbolitem9.SymbolName = "button yellow";
            multisymbolitem9.Transparent = false;
            symbolinterval9.Value = multisymbolitem9;
            symbolinterval10.End = 1D;
            symbolinterval10.Start = 1D;
            multisymbolitem10.SymbolName = "button orange";
            multisymbolitem10.Transparent = false;
            symbolinterval10.Value = multisymbolitem10;
            symbolinterval11.End = 3D;
            symbolinterval11.Start = 3D;
            multisymbolitem11.SymbolName = "button green";
            multisymbolitem11.Transparent = false;
            symbolinterval11.Value = multisymbolitem11;
            symbolinterval12.End = 4D;
            symbolinterval12.Start = 4D;
            multisymbolitem12.SymbolName = "button black";
            multisymbolitem12.Transparent = false;
            symbolinterval12.Value = multisymbolitem12;
            symbolinterval13.End = 5D;
            symbolinterval13.Start = 5D;
            multisymbolitem13.SymbolName = "button blue";
            multisymbolitem13.Transparent = false;
            symbolinterval13.Value = multisymbolitem13;
            symbolinterval14.End = 6D;
            symbolinterval14.Start = 6D;
            multisymbolitem14.SymbolName = "button purple";
            multisymbolitem14.Transparent = false;
            symbolinterval14.Value = multisymbolitem14;
            symbolinterval15.End = 7D;
            symbolinterval15.Start = 7D;
            multisymbolitem15.SymbolName = "button gray";
            multisymbolitem15.Transparent = false;
            symbolinterval15.Value = multisymbolitem15;
            symbolinterval16.End = 33D;
            symbolinterval16.Start = 33D;
            multisymbolitem16.SymbolName = "button red";
            multisymbolitem16.Transparent = false;
            symbolinterval16.Value = multisymbolitem16;
            symbolintervalmapper4.Intervals.Add(symbolinterval9);
            symbolintervalmapper4.Intervals.Add(symbolinterval10);
            symbolintervalmapper4.Intervals.Add(symbolinterval11);
            symbolintervalmapper4.Intervals.Add(symbolinterval12);
            symbolintervalmapper4.Intervals.Add(symbolinterval13);
            symbolintervalmapper4.Intervals.Add(symbolinterval14);
            symbolintervalmapper4.Intervals.Add(symbolinterval15);
            symbolintervalmapper4.Intervals.Add(symbolinterval16);
            this.m_MultiPicture.SymbolIntervalMapper = symbolintervalmapper4;
            this.m_MultiPicture.SymbolName = "button yellow";
            this.m_MultiPicture.Top = 143;
            this.m_MultiPicture.Value = 0D;
            this.m_MultiPicture.VisibleDynamicsValue = true;
            this.m_MultiPicture.Width = 100;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 600);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "Screen1";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_Screen1 = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_Screen1) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Button);
            this.DrawingPrimitives.Add(this.m_Button1);
            this.DrawingPrimitives.Add(this.m_Slider);
            this.DrawingPrimitives.Add(this.m_LinearMeter);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric1);
            this.DrawingPrimitives.Add(this.m_MultiPicture20);
            this.DrawingPrimitives.Add(this.m_MultiPicture);
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Slider)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_LinearMeter)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture20)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture)).EndInit();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Screen1));
            this.m_Button.Text = resources.GetText("Screen1.Button.Text", "Knapp 0");
            this.m_Button1.Text = resources.GetText("Screen1.Button1.Text", "Knapp 1");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_Screen1) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.tank"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric1.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.slider"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.lampe_1"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_MultiPicture.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding4 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.lampe_0"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_MultiPicture20.DataBindings.Add(dynamicBinding4);
            this.m_DynamicBindings.Add(dynamicBinding4);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding5 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.knapp_1"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button1.DataBindings.Add(dynamicBinding5);
            this.m_DynamicBindings.Add(dynamicBinding5);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding6 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.knapp_0"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button.DataBindings.Add(dynamicBinding6);
            this.m_DynamicBindings.Add(dynamicBinding6);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding7 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.tank"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_LinearMeter.DataBindings.Add(dynamicBinding7);
            this.m_DynamicBindings.Add(dynamicBinding7);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding8 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.slider"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Slider.DataBindings.Add(dynamicBinding8);
            this.m_DynamicBindings.Add(dynamicBinding8);
        }
    }
}
