//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class Alarmer : Neo.ApplicationFramework.Controls.Controls.Form {
        
        private Neo.ApplicationFramework.Controls.Alarm.AlarmViewer m_AlarmViewer;
        
        private Neo.ApplicationFramework.Controls.Controls.DigitalClockCF m_DigitalClock;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button11;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button10;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button13;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.EllipseCF m_Ellipse1;
        
        private Neo.ApplicationFramework.Controls.Controls.EllipseCF m_Ellipse3;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text8;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text9;
        
        private Neo.ApplicationFramework.Controls.Controls.EllipseCF m_Ellipse2;
        
        private Neo.ApplicationFramework.Controls.Controls.EllipseCF m_Ellipse;
        
        private bool m_Initialized_Alarmer;
        
        public Alarmer() {
            this.InitializeComponent();
            this.m_Button11.Click += new System.EventHandler(this.m_Button11_Action_Click);
            this.m_Button10.Click += new System.EventHandler(this.m_Button10_Action_Click);
            this.m_Button13.Click += new System.EventHandler(this.m_Button13_Action_Click);
            this.m_Button.Click += new System.EventHandler(this.m_Button_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        public Neo.ApplicationFramework.Controls.Script.AlarmViewerCFAdapter AlarmViewer {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AlarmViewerCFAdapter>(this.m_AlarmViewer);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter DigitalClock {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_DigitalClock);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button11 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button11);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button10 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button10);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button13 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button13);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Ellipse1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Ellipse1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Ellipse3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Ellipse3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text8 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text8);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text9 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text9);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Ellipse2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Ellipse2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Ellipse {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Ellipse);
            }
        }
        
        private void InitializeComponent() {
            Neo.ApplicationFramework.Controls.Logic.AlarmEventFilter alarmeventfilter1 = new Neo.ApplicationFramework.Controls.Logic.AlarmEventFilter();
            Neo.ApplicationFramework.Controls.Logic.AlarmEventFilterGroup alarmeventfiltergroup1 = new Neo.ApplicationFramework.Controls.Logic.AlarmEventFilterGroup();
            Neo.ApplicationFramework.Controls.Logic.AlarmColumnInfo alarmcolumninfo1 = new Neo.ApplicationFramework.Controls.Logic.AlarmColumnInfo();
            Neo.ApplicationFramework.Controls.Logic.AlarmColumnInfo alarmcolumninfo2 = new Neo.ApplicationFramework.Controls.Logic.AlarmColumnInfo();
            Neo.ApplicationFramework.Controls.Logic.AlarmColumnInfo alarmcolumninfo3 = new Neo.ApplicationFramework.Controls.Logic.AlarmColumnInfo();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_AlarmViewer = new Neo.ApplicationFramework.Controls.Alarm.AlarmViewer();
            this.m_DigitalClock = new Neo.ApplicationFramework.Controls.Controls.DigitalClockCF();
            this.m_Button11 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button10 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button13 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Ellipse1 = new Neo.ApplicationFramework.Controls.Controls.EllipseCF();
            this.m_Ellipse3 = new Neo.ApplicationFramework.Controls.Controls.EllipseCF();
            this.m_Text8 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text9 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Ellipse2 = new Neo.ApplicationFramework.Controls.Controls.EllipseCF();
            this.m_Ellipse = new Neo.ApplicationFramework.Controls.Controls.EllipseCF();
            ((System.ComponentModel.ISupportInitialize)(this.m_AlarmViewer)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_DigitalClock)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button11)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button10)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button13)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text8)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text9)).BeginInit();
            this.SuspendLayout();
            // 
            // Alarmer
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(227)))), ((int)(((byte)(227)))), ((int)(((byte)(227))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.ThreeDBorder;
            this.ControlBox = false;
            // 
            // m_AlarmViewer
            // 
            alarmeventfiltergroup1.Enabled = true;
            alarmeventfiltergroup1.Name = "Default";
            alarmeventfiltergroup1.ShowAcknowlegedAlarms = true;
            alarmeventfiltergroup1.ShowActiveAlarms = true;
            alarmeventfiltergroup1.ShowInactiveAlarms = true;
            alarmeventfiltergroup1.ShowNormalAlarms = true;
            alarmeventfilter1.Groups.Add(alarmeventfiltergroup1);
            alarmeventfilter1.MaximumAlarmRows = 100;
            this.m_AlarmViewer.AlarmEventFilter = alarmeventfilter1;
            this.m_AlarmViewer.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AlarmViewer.ButtonBackground = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(226)))), ((int)(((byte)(226))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AlarmViewer.ButtonHeight = 40;
            this.m_AlarmViewer.ButtonWidth = 130;
            this.m_AlarmViewer.ColumnHeaderBackground = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(211)))), ((int)(((byte)(211)))), ((int)(((byte)(211))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AlarmViewer.EnabledDynamicsValue = true;
            this.m_AlarmViewer.FontFamily = "Tahoma";
            this.m_AlarmViewer.FontSizePixels = 12;
            this.m_AlarmViewer.Foreground = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AlarmViewer.GridBackground = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AlarmViewer.Input = false;
            this.m_AlarmViewer.Location = new System.Drawing.Point(2, 59);
            this.m_AlarmViewer.Name = "m_AlarmViewer";
            this.m_AlarmViewer.PauseButtonIsVisible = false;
            this.m_AlarmViewer.ScreenOwnerName = "Alarmer";
            this.m_AlarmViewer.Size = new System.Drawing.Size(800, 493);
            this.m_AlarmViewer.TabIndex = 2147483647;
            alarmcolumninfo1.ColumnWidth = 80D;
            alarmcolumninfo1.HeaderName = "State";
            alarmcolumninfo1.MappingName = "DisplayState";
            alarmcolumninfo2.ColumnWidth = 150D;
            alarmcolumninfo2.HeaderName = "Active Time";
            alarmcolumninfo2.MappingName = "ActiveTime";
            alarmcolumninfo3.ColumnWidth = 250D;
            alarmcolumninfo3.HeaderName = "Text";
            alarmcolumninfo3.MappingName = "DisplayText";
            this.m_AlarmViewer.VisibleColumns = new Neo.ApplicationFramework.Interfaces.IColumnInfo[] {
                    ((Neo.ApplicationFramework.Interfaces.IColumnInfo)(alarmcolumninfo1)),
                    ((Neo.ApplicationFramework.Interfaces.IColumnInfo)(alarmcolumninfo2)),
                    ((Neo.ApplicationFramework.Interfaces.IColumnInfo)(alarmcolumninfo3))};
            this.m_AlarmViewer.VisibleDynamicsValue = true;
            // 
            // m_DigitalClock
            // 
            this.m_DigitalClock.BlinkDynamicsValue = false;
            this.m_DigitalClock.DisplayFormat = Neo.ApplicationFramework.Interfaces.DateTimeDisplayFormat.DateAndTime;
            this.m_DigitalClock.EnabledDynamicsValue = true;
            this.m_DigitalClock.FontSizePixels = 20;
            this.m_DigitalClock.Height = 30;
            this.m_DigitalClock.Left = 545;
            this.m_DigitalClock.Name = "m_DigitalClock";
            this.m_DigitalClock.ScreenOwnerName = "Alarmer";
            this.m_DigitalClock.ShowDayOfWeek = false;
            this.m_DigitalClock.ShowSeconds = true;
            this.m_DigitalClock.Text = "17.04.2026 11:22:55";
            this.m_DigitalClock.Top = 17;
            this.m_DigitalClock.VisibleDynamicsValue = true;
            this.m_DigitalClock.Width = 205;
            // 
            // m_Button11
            // 
            this.m_Button11.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_Button11.BlinkDynamicsValue = false;
            this.m_Button11.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button11.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button11.EnabledDynamicsValue = true;
            this.m_Button11.FontSizePixels = 17;
            this.m_Button11.ForceTransparency = true;
            this.m_Button11.Height = 40;
            this.m_Button11.IndicatorMargin = null;
            this.m_Button11.Left = 400;
            this.m_Button11.Name = "m_Button11";
            this.m_Button11.RequiresTransparency = true;
            this.m_Button11.ScreenOwnerName = "Alarmer";
            this.m_Button11.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_Button11.TextHeight = 21;
            this.m_Button11.TextValue = 0D;
            this.m_Button11.TextWidth = 191;
            this.m_Button11.Top = 560;
            this.m_Button11.Value = 0D;
            this.m_Button11.VisibleDynamicsValue = true;
            this.m_Button11.VisualPropertiesHashCode = -1413186907;
            this.m_Button11.Width = 201;
            // 
            // m_Button10
            // 
            this.m_Button10.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_Button10.BlinkDynamicsValue = false;
            this.m_Button10.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button10.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button10.EnabledDynamicsValue = true;
            this.m_Button10.FontSizePixels = 17;
            this.m_Button10.ForceTransparency = true;
            this.m_Button10.Height = 40;
            this.m_Button10.IndicatorMargin = null;
            this.m_Button10.Left = -1;
            this.m_Button10.Name = "m_Button10";
            this.m_Button10.RequiresTransparency = true;
            this.m_Button10.ScreenOwnerName = "Alarmer";
            this.m_Button10.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_Button10.TextHeight = 21;
            this.m_Button10.TextValue = 0D;
            this.m_Button10.TextWidth = 191;
            this.m_Button10.Top = 560;
            this.m_Button10.Value = 0D;
            this.m_Button10.VisibleDynamicsValue = true;
            this.m_Button10.VisualPropertiesHashCode = -1413186907;
            this.m_Button10.Width = 201;
            // 
            // m_Button13
            // 
            this.m_Button13.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_Button13.BlinkDynamicsValue = false;
            this.m_Button13.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button13.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button13.EnabledDynamicsValue = true;
            this.m_Button13.FontSizePixels = 17;
            this.m_Button13.ForceTransparency = true;
            this.m_Button13.Height = 40;
            this.m_Button13.IndicatorMargin = null;
            this.m_Button13.Left = 599;
            this.m_Button13.Name = "m_Button13";
            this.m_Button13.RequiresTransparency = true;
            this.m_Button13.ScreenOwnerName = "Alarmer";
            this.m_Button13.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_Button13.TextHeight = 21;
            this.m_Button13.TextValue = 0D;
            this.m_Button13.TextWidth = 191;
            this.m_Button13.Top = 560;
            this.m_Button13.Value = 0D;
            this.m_Button13.VisibleDynamicsValue = true;
            this.m_Button13.VisualPropertiesHashCode = -1413186907;
            this.m_Button13.Width = 201;
            // 
            // m_Button
            // 
            this.m_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_Button.BlinkDynamicsValue = false;
            this.m_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button.EnabledDynamicsValue = true;
            this.m_Button.FontSizePixels = 17;
            this.m_Button.ForceTransparency = true;
            this.m_Button.Height = 40;
            this.m_Button.IndicatorMargin = null;
            this.m_Button.Left = 199;
            this.m_Button.Name = "m_Button";
            this.m_Button.RequiresTransparency = true;
            this.m_Button.ScreenOwnerName = "Alarmer";
            this.m_Button.SymbolIntervalMapper = symbolintervalmapper4;
            this.m_Button.TextHeight = 21;
            this.m_Button.TextValue = 0D;
            this.m_Button.TextWidth = 191;
            this.m_Button.Top = 560;
            this.m_Button.Value = 0D;
            this.m_Button.VisibleDynamicsValue = true;
            this.m_Button.VisualPropertiesHashCode = -1413186907;
            this.m_Button.Width = 201;
            // 
            // m_Ellipse1
            // 
            this.m_Ellipse1.BlinkDynamicsValue = false;
            this.m_Ellipse1.BlinkInterval = 800;
            this.m_Ellipse1.EnabledDynamicsValue = true;
            this.m_Ellipse1.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(165)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse1.Height = 35;
            this.m_Ellipse1.Left = 422;
            this.m_Ellipse1.Name = "m_Ellipse1";
            this.m_Ellipse1.ScreenOwnerName = "Alarmer";
            this.m_Ellipse1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse1.Top = 563;
            this.m_Ellipse1.VisibleDynamicsValue = true;
            this.m_Ellipse1.Width = 35;
            // 
            // m_Ellipse3
            // 
            this.m_Ellipse3.BlinkDynamicsValue = false;
            this.m_Ellipse3.BlinkInterval = 800;
            this.m_Ellipse3.EnabledDynamicsValue = true;
            this.m_Ellipse3.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse3.Height = 35;
            this.m_Ellipse3.Left = 422;
            this.m_Ellipse3.Name = "m_Ellipse3";
            this.m_Ellipse3.ScreenOwnerName = "Alarmer";
            this.m_Ellipse3.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse3.Top = 563;
            this.m_Ellipse3.VisibleDynamicsValue = true;
            this.m_Ellipse3.Width = 35;
            // 
            // m_Text8
            // 
            this.m_Text8.BlinkDynamicsValue = false;
            this.m_Text8.EnabledDynamicsValue = true;
            this.m_Text8.FontSizePixels = 26;
            this.m_Text8.Height = 21;
            this.m_Text8.Left = 313;
            this.m_Text8.Name = "m_Text8";
            this.m_Text8.ScreenOwnerName = "Alarmer";
            this.m_Text8.Top = 13;
            this.m_Text8.VisibleDynamicsValue = true;
            this.m_Text8.Width = 35;
            // 
            // m_Text9
            // 
            this.m_Text9.BlinkDynamicsValue = false;
            this.m_Text9.EnabledDynamicsValue = true;
            this.m_Text9.FontSizePixels = 26;
            this.m_Text9.Height = 21;
            this.m_Text9.Left = 313;
            this.m_Text9.Name = "m_Text9";
            this.m_Text9.ScreenOwnerName = "Alarmer";
            this.m_Text9.Top = 13;
            this.m_Text9.VisibleDynamicsValue = true;
            this.m_Text9.Width = 35;
            // 
            // m_Ellipse2
            // 
            this.m_Ellipse2.BlinkDynamicsValue = false;
            this.m_Ellipse2.EnabledDynamicsValue = true;
            this.m_Ellipse2.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(165)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse2.Height = 35;
            this.m_Ellipse2.Left = 281;
            this.m_Ellipse2.Name = "m_Ellipse2";
            this.m_Ellipse2.ScreenOwnerName = "Alarmer";
            this.m_Ellipse2.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse2.Top = 14;
            this.m_Ellipse2.VisibleDynamicsValue = true;
            this.m_Ellipse2.Width = 35;
            // 
            // m_Ellipse
            // 
            this.m_Ellipse.BlinkDynamicsValue = false;
            this.m_Ellipse.EnabledDynamicsValue = true;
            this.m_Ellipse.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse.Height = 35;
            this.m_Ellipse.Left = 281;
            this.m_Ellipse.Name = "m_Ellipse";
            this.m_Ellipse.ScreenOwnerName = "Alarmer";
            this.m_Ellipse.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse.Top = 14;
            this.m_Ellipse.VisibleDynamicsValue = true;
            this.m_Ellipse.Width = 35;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 600);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "Alarmer";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_Alarmer = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_Alarmer) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            this.Controls.Add(this.m_AlarmViewer);
            ((System.ComponentModel.ISupportInitialize)(this.m_AlarmViewer)).EndInit();
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_DigitalClock);
            this.DrawingPrimitives.Add(this.m_Button11);
            this.DrawingPrimitives.Add(this.m_Button10);
            this.DrawingPrimitives.Add(this.m_Button13);
            this.DrawingPrimitives.Add(this.m_Button);
            this.DrawingPrimitives.Add(this.m_Ellipse1);
            this.DrawingPrimitives.Add(this.m_Ellipse3);
            this.DrawingPrimitives.Add(this.m_Text8);
            this.DrawingPrimitives.Add(this.m_Text9);
            this.DrawingPrimitives.Add(this.m_Ellipse2);
            this.DrawingPrimitives.Add(this.m_Ellipse);
            ((System.ComponentModel.ISupportInitialize)(this.m_DigitalClock)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button11)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button10)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button13)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text8)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text9)).EndInit();
        }
        
        private void m_Button11_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button11", "Click", "Show Screen", "Alarmer", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.Alarmer.Show();
        }
        
        private void m_Button10_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button10", "Click", "Show Screen", "Hjem", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.Hjem.Show();
        }
        
        private void m_Button13_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button13", "Click", "Show Screen", "Trender", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.Trender.Show();
        }
        
        private void m_Button_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button", "Click", "Show Screen", "Regulator", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.Regulator.Show();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Alarmer));
            this.m_Button11.Text = resources.GetText("Alarmer.Button11.Text", "Alarmer");
            this.m_Button10.Text = resources.GetText("Alarmer.Button10.Text", "Hjem");
            this.m_Button13.Text = resources.GetText("Alarmer.Button13.Text", "Trender");
            this.m_Button.Text = resources.GetText("Alarmer.Button.Text", "Regulering");
            this.m_Text8.Text = resources.GetText("Alarmer.Text8.Text", "Alarm");
            this.m_Text9.Text = resources.GetText("Alarmer.Text9.Text", "Alarm");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_Alarmer) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Alarm_synling"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Text9.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Alarm_synling"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Ellipse2.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Kritisk_alarm_synling"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Ellipse.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding4 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Kritisk_alarm_synling"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Text8.DataBindings.Add(dynamicBinding4);
            this.m_DynamicBindings.Add(dynamicBinding4);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding5 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Alarm_synling"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Ellipse1.DataBindings.Add(dynamicBinding5);
            this.m_DynamicBindings.Add(dynamicBinding5);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding6 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("IsBlinkEnabled", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Kritisk_alarm_synling"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Ellipse3.DataBindings.Add(dynamicBinding6);
            this.m_DynamicBindings.Add(dynamicBinding6);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding7 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Kritisk_alarm_synling"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Ellipse3.DataBindings.Add(dynamicBinding7);
            this.m_DynamicBindings.Add(dynamicBinding7);
        }
    }
}
