//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	using Neo.ApplicationFramework.Tools.Alarm;
	
	
	public partial class AlarmServer : Neo.ApplicationFramework.Tools.Alarm.AlarmServer
	{
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmGroup m_Default;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Default_Prosessverdi_kritisk_høy;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Default_Prosessverd_høy;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Default_Prosessverdi2_lav;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Default_Prosessverdi3_kritisk_lav;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Default_Prosessverdi4;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Default_Prosessverdi5;
		
		public AlarmServer()
		{
			this.InitializeComponent();
			this.Default_Prosessverdi_kritisk_høy.AlarmActive += new System.EventHandler(this.Default_Prosessverdi_kritisk_høy_Action_AlarmActive);
			this.Default_Prosessverd_høy.AlarmActive += new System.EventHandler(this.Default_Prosessverd_høy_Action_AlarmActive);
			this.Default_Prosessverdi2_lav.AlarmActive += new System.EventHandler(this.Default_Prosessverdi2_lav_Action_AlarmActive);
			this.Default_Prosessverdi3_kritisk_lav.AlarmActive += new System.EventHandler(this.Default_Prosessverdi3_kritisk_lav_Action_AlarmActive);
			this.ApplyLanguageInternal();
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmGroup Default
		{
			get
			{
				return this.m_Default;
			}
			set
			{
				this.m_Default = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Default_Prosessverdi_kritisk_høy
		{
			get
			{
				return this.m_Default_Prosessverdi_kritisk_høy;
			}
			set
			{
				this.m_Default_Prosessverdi_kritisk_høy = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Default_Prosessverd_høy
		{
			get
			{
				return this.m_Default_Prosessverd_høy;
			}
			set
			{
				this.m_Default_Prosessverd_høy = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Default_Prosessverdi2_lav
		{
			get
			{
				return this.m_Default_Prosessverdi2_lav;
			}
			set
			{
				this.m_Default_Prosessverdi2_lav = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Default_Prosessverdi3_kritisk_lav
		{
			get
			{
				return this.m_Default_Prosessverdi3_kritisk_lav;
			}
			set
			{
				this.m_Default_Prosessverdi3_kritisk_lav = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Default_Prosessverdi4
		{
			get
			{
				return this.m_Default_Prosessverdi4;
			}
			set
			{
				this.m_Default_Prosessverdi4 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Default_Prosessverdi5
		{
			get
			{
				return this.m_Default_Prosessverdi5;
			}
			set
			{
				this.m_Default_Prosessverdi5 = value;
			}
		}
		
		private void InitializeComponent()
		{
			this.InitializeObjectCreations();
			this.InitializeBeginInits();
			this.InitializeObjects();
			this.InitializeEndInits();
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public override void ConnectDataBindings()
		{
			base.ConnectDataBindings();
			this.Default_Prosessverdi3_kritisk_lav.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.Alarm_kritisk_lav"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, null));
			this.Default_Prosessverdi4.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.Alarm_synling"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, null));
			this.Default_Prosessverdi5.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.Kritisk_alarm_synling"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, null));
			this.Default_Prosessverdi_kritisk_høy.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.Alarm_kritisk_høy"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, null));
			this.Default_Prosessverd_høy.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.Alarm_høy"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, null));
			this.Default_Prosessverdi2_lav.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.Alarm_lav"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, null));
		}
		
		private void InitializeObjectCreations()
		{
			this.Default = new Neo.ApplicationFramework.Tools.Alarm.AlarmGroup();
			this.Default_Prosessverdi_kritisk_høy = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Default_Prosessverd_høy = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Default_Prosessverdi2_lav = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Default_Prosessverdi3_kritisk_lav = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Default_Prosessverdi4 = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
			this.Default_Prosessverdi5 = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
		}
		
		private void InitializeBeginInits()
		{
			((System.ComponentModel.ISupportInitialize)(this.Default_Prosessverdi_kritisk_høy)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Default_Prosessverd_høy)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Default_Prosessverdi2_lav)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Default_Prosessverdi3_kritisk_lav)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Default_Prosessverdi4)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Default_Prosessverdi5)).BeginInit();
		}
		
		private void InitializeEndInits()
		{
			((System.ComponentModel.ISupportInitialize)(this.Default_Prosessverdi_kritisk_høy)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Default_Prosessverd_høy)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Default_Prosessverdi2_lav)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Default_Prosessverdi3_kritisk_lav)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Default_Prosessverdi4)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Default_Prosessverdi5)).EndInit();
		}
		
		private void InitializeObjects()
		{
			this.Default.AcknowledgeBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(67)))), ((int)(((byte)(127)))), ((int)(((byte)(70)))));
			this.Default.AcknowledgeForeColor = System.Drawing.Color.Black;
			this.Default.ActiveBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(19)))), ((int)(((byte)(41)))));
			this.Default.ActiveForeColor = System.Drawing.Color.Black;
			this.Default_Prosessverdi_kritisk_høy.AcknowledgeRequired = true;
			this.Default_Prosessverdi_kritisk_høy.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Default_Prosessverdi_kritisk_høy.Contacts = null;
			this.Default_Prosessverdi_kritisk_høy.DefaultText = "KRITISK HØY";
			this.Default_Prosessverdi_kritisk_høy.DisplayName = "Prosessverdi_kritisk_høy";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString dynamicstring1 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			dynamicstring1.Text = "KRITISK HØY";
			this.Default_Prosessverdi_kritisk_høy.DynamicString = dynamicstring1;
			this.Default_Prosessverdi_kritisk_høy.EnableDistribution = false;
			this.Default_Prosessverdi_kritisk_høy.GroupId = new System.Guid("eea00163-70bc-437c-b0bc-b057ade8de2b");
			this.Default_Prosessverdi_kritisk_høy.GroupName = "Default";
			this.Default_Prosessverdi_kritisk_høy.History = true;
			this.Default_Prosessverdi_kritisk_høy.IsDigitalValue = false;
			this.Default_Prosessverdi_kritisk_høy.Name = "Default_Prosessverdi_kritisk_høy";
			this.Default_Prosessverdi_kritisk_høy.OutputDevices = null;
			this.Default_Prosessverdi_kritisk_høy.RepeatCount = false;
			this.Default_Prosessverdi_kritisk_høy.TriggerValue = 1;
			this.Default_Prosessverd_høy.AcknowledgeRequired = true;
			this.Default_Prosessverd_høy.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Default_Prosessverd_høy.Contacts = null;
			this.Default_Prosessverd_høy.DefaultText = "HØY";
			this.Default_Prosessverd_høy.DisplayName = "Prosessverd_høy";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString dynamicstring2 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			dynamicstring2.Text = "HØY";
			this.Default_Prosessverd_høy.DynamicString = dynamicstring2;
			this.Default_Prosessverd_høy.EnableDistribution = false;
			this.Default_Prosessverd_høy.GroupId = new System.Guid("eea00163-70bc-437c-b0bc-b057ade8de2b");
			this.Default_Prosessverd_høy.GroupName = "Default";
			this.Default_Prosessverd_høy.History = true;
			this.Default_Prosessverd_høy.IsDigitalValue = false;
			this.Default_Prosessverd_høy.Name = "Default_Prosessverd_høy";
			this.Default_Prosessverd_høy.OutputDevices = null;
			this.Default_Prosessverd_høy.RepeatCount = false;
			this.Default_Prosessverd_høy.TriggerValue = 1;
			this.Default_Prosessverdi2_lav.AcknowledgeRequired = true;
			this.Default_Prosessverdi2_lav.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Default_Prosessverdi2_lav.Contacts = null;
			this.Default_Prosessverdi2_lav.DefaultText = "LAV";
			this.Default_Prosessverdi2_lav.DisplayName = "Prosessverdi2_lav";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString dynamicstring3 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			dynamicstring3.Text = "LAV";
			this.Default_Prosessverdi2_lav.DynamicString = dynamicstring3;
			this.Default_Prosessverdi2_lav.EnableDistribution = false;
			this.Default_Prosessverdi2_lav.GroupId = new System.Guid("eea00163-70bc-437c-b0bc-b057ade8de2b");
			this.Default_Prosessverdi2_lav.GroupName = "Default";
			this.Default_Prosessverdi2_lav.History = true;
			this.Default_Prosessverdi2_lav.IsDigitalValue = false;
			this.Default_Prosessverdi2_lav.Name = "Default_Prosessverdi2_lav";
			this.Default_Prosessverdi2_lav.OutputDevices = null;
			this.Default_Prosessverdi2_lav.RepeatCount = false;
			this.Default_Prosessverdi2_lav.TriggerValue = 1;
			this.Default_Prosessverdi3_kritisk_lav.AcknowledgeRequired = true;
			this.Default_Prosessverdi3_kritisk_lav.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Default_Prosessverdi3_kritisk_lav.Contacts = null;
			this.Default_Prosessverdi3_kritisk_lav.DefaultText = "KRITISK LAV";
			this.Default_Prosessverdi3_kritisk_lav.DisplayName = "Prosessverdi3_kritisk_lav";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString dynamicstring4 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			dynamicstring4.Text = "KRITISK LAV";
			this.Default_Prosessverdi3_kritisk_lav.DynamicString = dynamicstring4;
			this.Default_Prosessverdi3_kritisk_lav.EnableDistribution = false;
			this.Default_Prosessverdi3_kritisk_lav.GroupId = new System.Guid("eea00163-70bc-437c-b0bc-b057ade8de2b");
			this.Default_Prosessverdi3_kritisk_lav.GroupName = "Default";
			this.Default_Prosessverdi3_kritisk_lav.History = true;
			this.Default_Prosessverdi3_kritisk_lav.IsDigitalValue = false;
			this.Default_Prosessverdi3_kritisk_lav.Name = "Default_Prosessverdi3_kritisk_lav";
			this.Default_Prosessverdi3_kritisk_lav.OutputDevices = null;
			this.Default_Prosessverdi3_kritisk_lav.RepeatCount = false;
			this.Default_Prosessverdi3_kritisk_lav.TriggerValue = 1;
			this.Default_Prosessverdi4.AcknowledgeRequired = true;
			this.Default_Prosessverdi4.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Default_Prosessverdi4.Contacts = null;
			this.Default_Prosessverdi4.DefaultText = "Alarm";
			this.Default_Prosessverdi4.DisplayName = "Prosessverdi4";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString dynamicstring5 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			dynamicstring5.Text = "Alarm";
			this.Default_Prosessverdi4.DynamicString = dynamicstring5;
			this.Default_Prosessverdi4.EnableDistribution = false;
			this.Default_Prosessverdi4.GroupId = new System.Guid("eea00163-70bc-437c-b0bc-b057ade8de2b");
			this.Default_Prosessverdi4.GroupName = "Default";
			this.Default_Prosessverdi4.History = true;
			this.Default_Prosessverdi4.IsDigitalValue = false;
			this.Default_Prosessverdi4.Name = "Default_Prosessverdi4";
			this.Default_Prosessverdi4.OutputDevices = null;
			this.Default_Prosessverdi4.RepeatCount = false;
			this.Default_Prosessverdi4.TriggerValue = 1;
			this.Default_Prosessverdi5.AcknowledgeRequired = true;
			this.Default_Prosessverdi5.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.EqualTo;
			this.Default_Prosessverdi5.Contacts = null;
			this.Default_Prosessverdi5.DefaultText = "Alarm_kritisk";
			this.Default_Prosessverdi5.DisplayName = "Prosessverdi5";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString dynamicstring6 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			dynamicstring6.Text = "Alarm_kritisk";
			this.Default_Prosessverdi5.DynamicString = dynamicstring6;
			this.Default_Prosessverdi5.EnableDistribution = false;
			this.Default_Prosessverdi5.GroupId = new System.Guid("eea00163-70bc-437c-b0bc-b057ade8de2b");
			this.Default_Prosessverdi5.GroupName = "Default";
			this.Default_Prosessverdi5.History = true;
			this.Default_Prosessverdi5.IsDigitalValue = false;
			this.Default_Prosessverdi5.Name = "Default_Prosessverdi5";
			this.Default_Prosessverdi5.OutputDevices = null;
			this.Default_Prosessverdi5.RepeatCount = false;
			this.Default_Prosessverdi5.TriggerValue = 1;
			this.Default.AlarmItems.Add(this.Default_Prosessverdi_kritisk_høy);
			this.Default.AlarmItems.Add(this.Default_Prosessverd_høy);
			this.Default.AlarmItems.Add(this.Default_Prosessverdi2_lav);
			this.Default.AlarmItems.Add(this.Default_Prosessverdi3_kritisk_lav);
			this.Default.AlarmItems.Add(this.Default_Prosessverdi4);
			this.Default.AlarmItems.Add(this.Default_Prosessverdi5);
			this.Default.EnableDistribution = false;
			this.Default.InactiveBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(241)))), ((int)(((byte)(204)))), ((int)(((byte)(71)))));
			this.Default.InactiveForeColor = System.Drawing.Color.Black;
			this.Default.Name = "Default";
			this.Default.NormalBackColor = System.Drawing.SystemColors.Window;
			this.Default.NormalForeColor = System.Drawing.Color.Black;
			this.AlarmGroups.Add(this.Default);
			this.StorageEvent.AcknowledgeTime = null;
			this.StorageEvent.ActiveTime = null;
			this.StorageEvent.AlarmGroupName = "";
			this.StorageEvent.AlarmGroupText = "";
			this.StorageEvent.AlarmItemId = new System.Guid("00000000-0000-0000-0000-000000000000");
			this.StorageEvent.Count = 0;
			this.StorageEvent.DisplayText = "";
			this.StorageEvent.EnableDistribution = false;
			this.StorageEvent.ForceToList = false;
			this.StorageEvent.History = false;
			this.StorageEvent.InActiveTime = null;
			this.StorageEvent.NormalTime = null;
			this.StorageEvent.RepeatCount = false;
			this.StorageEvent.State = Neo.ApplicationFramework.Interfaces.AlarmState.Normal;
			this.StorageEvent.TableName = "AlarmServer";
			this.StorageEvent.Text = "";
		}
		
		private void Default_Prosessverdi_kritisk_høy_Action_AlarmActive(object sender, System.EventArgs e)
		{
			Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("Default_Prosessverdi_kritisk_høy", "AlarmActive", "Set Analog", "Tags.Kritisk_alarm_synling", "");
			Neo.ApplicationFramework.Generated.Globals.Tags.Kritisk_alarm_synling.SetAnalog(1);
		}
		
		private void Default_Prosessverd_høy_Action_AlarmActive(object sender, System.EventArgs e)
		{
			Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("Default_Prosessverd_høy", "AlarmActive", "Set Analog", "Tags.Alarm_synling", "");
			Neo.ApplicationFramework.Generated.Globals.Tags.Alarm_synling.SetAnalog(1);
		}
		
		private void Default_Prosessverdi2_lav_Action_AlarmActive(object sender, System.EventArgs e)
		{
			Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("Default_Prosessverdi2_lav", "AlarmActive", "Set Analog", "Tags.Alarm_synling", "");
			Neo.ApplicationFramework.Generated.Globals.Tags.Alarm_synling.SetAnalog(1);
		}
		
		private void Default_Prosessverdi3_kritisk_lav_Action_AlarmActive(object sender, System.EventArgs e)
		{
			Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("Default_Prosessverdi3_kritisk_lav", "AlarmActive", "Set Analog", "Tags.Kritisk_alarm_synling", "");
			Neo.ApplicationFramework.Generated.Globals.Tags.Kritisk_alarm_synling.SetAnalog(1);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(AlarmServer));
			this.m_Default.Text = resources.GetText("AlarmServer.Default.Text", "Default");
			this.m_Default_Prosessverdi_kritisk_høy.StaticText = resources.GetText("AlarmServer.Default_Prosessverdi_kritisk_høy.StaticText", "KRITISK HØY");
			this.m_Default_Prosessverd_høy.StaticText = resources.GetText("AlarmServer.Default_Prosessverd_høy.StaticText", "HØY");
			this.m_Default_Prosessverdi2_lav.StaticText = resources.GetText("AlarmServer.Default_Prosessverdi2_lav.StaticText", "LAV");
			this.m_Default_Prosessverdi3_kritisk_lav.StaticText = resources.GetText("AlarmServer.Default_Prosessverdi3_kritisk_lav.StaticText", "KRITISK LAV");
			this.m_Default_Prosessverdi4.StaticText = resources.GetText("AlarmServer.Default_Prosessverdi4.StaticText", "Alarm");
			this.m_Default_Prosessverdi5.StaticText = resources.GetText("AlarmServer.Default_Prosessverdi5.StaticText", "Alarm_kritisk");
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected override void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
			base.ApplyLanguage();
		}
	}
}
