//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class Trender : Neo.ApplicationFramework.Controls.Controls.Form {
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text1;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text2;
        
        private Neo.ApplicationFramework.Controls.Trend.TrendViewerCF m_TrendViewer;
        
        private Neo.ApplicationFramework.Controls.Controls.DigitalClockCF m_DigitalClock;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button11;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button10;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button13;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.EllipseCF m_Ellipse1;
        
        private Neo.ApplicationFramework.Controls.Controls.EllipseCF m_Ellipse3;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text8;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text9;
        
        private Neo.ApplicationFramework.Controls.Controls.EllipseCF m_Ellipse2;
        
        private Neo.ApplicationFramework.Controls.Controls.EllipseCF m_Ellipse;
        
        private bool m_Initialized_Trender;
        
        public Trender() {
            this.InitializeComponent();
            this.m_Button11.Click += new System.EventHandler(this.m_Button11_Action_Click);
            this.m_Button10.Click += new System.EventHandler(this.m_Button10_Action_Click);
            this.m_Button13.Click += new System.EventHandler(this.m_Button13_Action_Click);
            this.m_Button.Click += new System.EventHandler(this.m_Button_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text2);
            }
        }
        
        public Neo.ApplicationFramework.Controls.Script.TrendCFAdapterBase TrendViewer {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TrendCFAdapterBase>(this.m_TrendViewer);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter DigitalClock {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_DigitalClock);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button11 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button11);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button10 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button10);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button13 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button13);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Ellipse1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Ellipse1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Ellipse3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Ellipse3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text8 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text8);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text9 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text9);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Ellipse2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Ellipse2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Ellipse {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Ellipse);
            }
        }
        
        private void InitializeComponent() {
            Neo.ApplicationFramework.Controls.Trend.CurveCF curvecf1 = new Neo.ApplicationFramework.Controls.Trend.CurveCF();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text1 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text2 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_TrendViewer = new Neo.ApplicationFramework.Controls.Trend.TrendViewerCF();
            this.m_DigitalClock = new Neo.ApplicationFramework.Controls.Controls.DigitalClockCF();
            this.m_Button11 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button10 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button13 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Ellipse1 = new Neo.ApplicationFramework.Controls.Controls.EllipseCF();
            this.m_Ellipse3 = new Neo.ApplicationFramework.Controls.Controls.EllipseCF();
            this.m_Text8 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text9 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Ellipse2 = new Neo.ApplicationFramework.Controls.Controls.EllipseCF();
            this.m_Ellipse = new Neo.ApplicationFramework.Controls.Controls.EllipseCF();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_TrendViewer)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_DigitalClock)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button11)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button10)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button13)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text8)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text9)).BeginInit();
            this.SuspendLayout();
            // 
            // Trender
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(227)))), ((int)(((byte)(227)))), ((int)(((byte)(227))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.ThreeDBorder;
            this.ControlBox = false;
            // 
            // m_Text
            // 
            this.m_Text.BlinkDynamicsValue = false;
            this.m_Text.EnabledDynamicsValue = true;
            this.m_Text.FontSizePixels = 20;
            this.m_Text.Height = 21;
            this.m_Text.Left = 668;
            this.m_Text.Name = "m_Text";
            this.m_Text.ScreenOwnerName = "Trender";
            this.m_Text.Top = 161;
            this.m_Text.VisibleDynamicsValue = true;
            this.m_Text.Width = 54;
            // 
            // m_Text1
            // 
            this.m_Text1.BlinkDynamicsValue = false;
            this.m_Text1.EnabledDynamicsValue = true;
            this.m_Text1.FontSizePixels = 20;
            this.m_Text1.Height = 6;
            this.m_Text1.Left = 671;
            this.m_Text1.Name = "m_Text1";
            this.m_Text1.ScreenOwnerName = "Trender";
            this.m_Text1.Top = 153;
            this.m_Text1.VisibleDynamicsValue = true;
            this.m_Text1.Width = 2;
            // 
            // m_Text2
            // 
            this.m_Text2.BlinkDynamicsValue = false;
            this.m_Text2.EnabledDynamicsValue = true;
            this.m_Text2.FontSizePixels = 20;
            this.m_Text2.Height = 21;
            this.m_Text2.Left = 666;
            this.m_Text2.Name = "m_Text2";
            this.m_Text2.ScreenOwnerName = "Trender";
            this.m_Text2.Top = 200;
            this.m_Text2.VisibleDynamicsValue = true;
            this.m_Text2.Width = 68;
            // 
            // m_TrendViewer
            // 
            this.m_TrendViewer.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_TrendViewer.BlinkDynamicsValue = false;
            curvecf1.BlinkDynamicsValue = false;
            curvecf1.Color = System.Drawing.Color.Red;
            curvecf1.DataSourceName = "Tags.Pådrag";
            curvecf1.DisplayName = "Curve";
            curvecf1.EnabledDynamicsValue = true;
            curvecf1.Height = 418;
            curvecf1.ScreenOwnerName = null;
            curvecf1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.Red, System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            curvecf1.VisibleDynamicsValue = true;
            curvecf1.Width = 569;
            this.m_TrendViewer.Curves.Add(curvecf1);
            this.m_TrendViewer.EnabledDynamicsValue = true;
            this.m_TrendViewer.FontSizePixels = 11;
            this.m_TrendViewer.ForceTransparency = false;
            this.m_TrendViewer.Foreground = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_TrendViewer.GridLineColor = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_TrendViewer.Height = 499;
            this.m_TrendViewer.IndicatorMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(52D, 33.791D, 52D, 47D);
            this.m_TrendViewer.Left = -11;
            this.m_TrendViewer.Name = "m_TrendViewer";
            this.m_TrendViewer.RequiresTransparency = false;
            this.m_TrendViewer.ScaleColor = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_TrendViewer.ScreenOwnerName = "Trender";
            this.m_TrendViewer.TimeOffset = System.TimeSpan.Parse("00:00:00");
            this.m_TrendViewer.TimeRange = System.TimeSpan.Parse("00:10:00");
            this.m_TrendViewer.TimeScaleMaximum = 39083.5D;
            this.m_TrendViewer.TimeScaleMinimum = 39083.493055555555D;
            this.m_TrendViewer.TimeTextScaleMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(52D, 469D, 52D, 16.723333333333358D);
            this.m_TrendViewer.Top = 54;
            this.m_TrendViewer.Value = 0D;
            this.m_TrendViewer.ValueMajorScaleMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(32D, 33.791D, 631D, 47D);
            this.m_TrendViewer.ValueMajorScaleMaxMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(631D, 33.791D, 32D, 47D);
            this.m_TrendViewer.ValueMinorScaleMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(37D, 33.791D, 631D, 47D);
            this.m_TrendViewer.ValueMinorScaleMaxMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(631D, 33.791D, 37D, 47D);
            this.m_TrendViewer.ValueScaleMajorTickCount = 11;
            this.m_TrendViewer.ValueScaleMaximum = 100D;
            this.m_TrendViewer.ValueScaleMinimum = 0D;
            this.m_TrendViewer.ValueScaleMinorTickCount = 4;
            this.m_TrendViewer.ValueTextScaleMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(11.989999999999998D, 33.791D, 643D, 47D);
            this.m_TrendViewer.ValueTextScaleMaxMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(643D, 33.791D, 11.990000000000009D, 47D);
            this.m_TrendViewer.VisibleDynamicsValue = true;
            this.m_TrendViewer.Width = 673;
            // 
            // m_DigitalClock
            // 
            this.m_DigitalClock.BlinkDynamicsValue = false;
            this.m_DigitalClock.DisplayFormat = Neo.ApplicationFramework.Interfaces.DateTimeDisplayFormat.DateAndTime;
            this.m_DigitalClock.EnabledDynamicsValue = true;
            this.m_DigitalClock.FontSizePixels = 20;
            this.m_DigitalClock.Height = 30;
            this.m_DigitalClock.Left = 542;
            this.m_DigitalClock.Name = "m_DigitalClock";
            this.m_DigitalClock.ScreenOwnerName = "Trender";
            this.m_DigitalClock.ShowDayOfWeek = false;
            this.m_DigitalClock.ShowSeconds = true;
            this.m_DigitalClock.Text = "20.03.2026 13:26:29";
            this.m_DigitalClock.Top = 13;
            this.m_DigitalClock.VisibleDynamicsValue = true;
            this.m_DigitalClock.Width = 205;
            // 
            // m_Button11
            // 
            this.m_Button11.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_Button11.BlinkDynamicsValue = false;
            this.m_Button11.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button11.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button11.EnabledDynamicsValue = true;
            this.m_Button11.FontSizePixels = 17;
            this.m_Button11.ForceTransparency = true;
            this.m_Button11.Height = 40;
            this.m_Button11.IndicatorMargin = null;
            this.m_Button11.Left = 400;
            this.m_Button11.Name = "m_Button11";
            this.m_Button11.RequiresTransparency = true;
            this.m_Button11.ScreenOwnerName = "Trender";
            this.m_Button11.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_Button11.TextHeight = 21;
            this.m_Button11.TextValue = 0D;
            this.m_Button11.TextWidth = 191;
            this.m_Button11.Top = 560;
            this.m_Button11.Value = 0D;
            this.m_Button11.VisibleDynamicsValue = true;
            this.m_Button11.VisualPropertiesHashCode = -1413186907;
            this.m_Button11.Width = 201;
            // 
            // m_Button10
            // 
            this.m_Button10.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_Button10.BlinkDynamicsValue = false;
            this.m_Button10.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button10.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button10.EnabledDynamicsValue = true;
            this.m_Button10.FontSizePixels = 17;
            this.m_Button10.ForceTransparency = true;
            this.m_Button10.Height = 40;
            this.m_Button10.IndicatorMargin = null;
            this.m_Button10.Left = -1;
            this.m_Button10.Name = "m_Button10";
            this.m_Button10.RequiresTransparency = true;
            this.m_Button10.ScreenOwnerName = "Trender";
            this.m_Button10.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_Button10.TextHeight = 21;
            this.m_Button10.TextValue = 0D;
            this.m_Button10.TextWidth = 191;
            this.m_Button10.Top = 560;
            this.m_Button10.Value = 0D;
            this.m_Button10.VisibleDynamicsValue = true;
            this.m_Button10.VisualPropertiesHashCode = -1413186907;
            this.m_Button10.Width = 201;
            // 
            // m_Button13
            // 
            this.m_Button13.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_Button13.BlinkDynamicsValue = false;
            this.m_Button13.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button13.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button13.EnabledDynamicsValue = true;
            this.m_Button13.FontSizePixels = 17;
            this.m_Button13.ForceTransparency = true;
            this.m_Button13.Height = 40;
            this.m_Button13.IndicatorMargin = null;
            this.m_Button13.Left = 599;
            this.m_Button13.Name = "m_Button13";
            this.m_Button13.RequiresTransparency = true;
            this.m_Button13.ScreenOwnerName = "Trender";
            this.m_Button13.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_Button13.TextHeight = 21;
            this.m_Button13.TextValue = 0D;
            this.m_Button13.TextWidth = 191;
            this.m_Button13.Top = 560;
            this.m_Button13.Value = 0D;
            this.m_Button13.VisibleDynamicsValue = true;
            this.m_Button13.VisualPropertiesHashCode = -1413186907;
            this.m_Button13.Width = 201;
            // 
            // m_Button
            // 
            this.m_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_Button.BlinkDynamicsValue = false;
            this.m_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button.EnabledDynamicsValue = true;
            this.m_Button.FontSizePixels = 17;
            this.m_Button.ForceTransparency = true;
            this.m_Button.Height = 40;
            this.m_Button.IndicatorMargin = null;
            this.m_Button.Left = 199;
            this.m_Button.Name = "m_Button";
            this.m_Button.RequiresTransparency = true;
            this.m_Button.ScreenOwnerName = "Trender";
            this.m_Button.SymbolIntervalMapper = symbolintervalmapper4;
            this.m_Button.TextHeight = 21;
            this.m_Button.TextValue = 0D;
            this.m_Button.TextWidth = 191;
            this.m_Button.Top = 560;
            this.m_Button.Value = 0D;
            this.m_Button.VisibleDynamicsValue = true;
            this.m_Button.VisualPropertiesHashCode = -1413186907;
            this.m_Button.Width = 201;
            // 
            // m_Ellipse1
            // 
            this.m_Ellipse1.BlinkDynamicsValue = false;
            this.m_Ellipse1.BlinkInterval = 800;
            this.m_Ellipse1.EnabledDynamicsValue = true;
            this.m_Ellipse1.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(165)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse1.Height = 35;
            this.m_Ellipse1.Left = 422;
            this.m_Ellipse1.Name = "m_Ellipse1";
            this.m_Ellipse1.ScreenOwnerName = "Trender";
            this.m_Ellipse1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse1.Top = 563;
            this.m_Ellipse1.VisibleDynamicsValue = true;
            this.m_Ellipse1.Width = 35;
            // 
            // m_Ellipse3
            // 
            this.m_Ellipse3.BlinkDynamicsValue = false;
            this.m_Ellipse3.BlinkInterval = 800;
            this.m_Ellipse3.EnabledDynamicsValue = true;
            this.m_Ellipse3.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse3.Height = 35;
            this.m_Ellipse3.Left = 422;
            this.m_Ellipse3.Name = "m_Ellipse3";
            this.m_Ellipse3.ScreenOwnerName = "Trender";
            this.m_Ellipse3.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse3.Top = 563;
            this.m_Ellipse3.VisibleDynamicsValue = true;
            this.m_Ellipse3.Width = 35;
            // 
            // m_Text8
            // 
            this.m_Text8.BlinkDynamicsValue = false;
            this.m_Text8.EnabledDynamicsValue = true;
            this.m_Text8.FontSizePixels = 26;
            this.m_Text8.Height = 21;
            this.m_Text8.Left = 303;
            this.m_Text8.Name = "m_Text8";
            this.m_Text8.ScreenOwnerName = "Trender";
            this.m_Text8.Top = 8;
            this.m_Text8.VisibleDynamicsValue = true;
            this.m_Text8.Width = 35;
            // 
            // m_Text9
            // 
            this.m_Text9.BlinkDynamicsValue = false;
            this.m_Text9.EnabledDynamicsValue = true;
            this.m_Text9.FontSizePixels = 26;
            this.m_Text9.Height = 21;
            this.m_Text9.Left = 303;
            this.m_Text9.Name = "m_Text9";
            this.m_Text9.ScreenOwnerName = "Trender";
            this.m_Text9.Top = 8;
            this.m_Text9.VisibleDynamicsValue = true;
            this.m_Text9.Width = 35;
            // 
            // m_Ellipse2
            // 
            this.m_Ellipse2.BlinkDynamicsValue = false;
            this.m_Ellipse2.EnabledDynamicsValue = true;
            this.m_Ellipse2.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(165)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse2.Height = 35;
            this.m_Ellipse2.Left = 271;
            this.m_Ellipse2.Name = "m_Ellipse2";
            this.m_Ellipse2.ScreenOwnerName = "Trender";
            this.m_Ellipse2.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse2.Top = 9;
            this.m_Ellipse2.VisibleDynamicsValue = true;
            this.m_Ellipse2.Width = 35;
            // 
            // m_Ellipse
            // 
            this.m_Ellipse.BlinkDynamicsValue = false;
            this.m_Ellipse.EnabledDynamicsValue = true;
            this.m_Ellipse.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse.Height = 35;
            this.m_Ellipse.Left = 271;
            this.m_Ellipse.Name = "m_Ellipse";
            this.m_Ellipse.ScreenOwnerName = "Trender";
            this.m_Ellipse.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse.Top = 9;
            this.m_Ellipse.VisibleDynamicsValue = true;
            this.m_Ellipse.Width = 35;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 600);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "Trender";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_Trender = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_Trender) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Text);
            this.DrawingPrimitives.Add(this.m_Text1);
            this.DrawingPrimitives.Add(this.m_Text2);
            this.DrawingPrimitives.Add(this.m_TrendViewer);
            this.DrawingPrimitives.Add(this.m_DigitalClock);
            this.DrawingPrimitives.Add(this.m_Button11);
            this.DrawingPrimitives.Add(this.m_Button10);
            this.DrawingPrimitives.Add(this.m_Button13);
            this.DrawingPrimitives.Add(this.m_Button);
            this.DrawingPrimitives.Add(this.m_Ellipse1);
            this.DrawingPrimitives.Add(this.m_Ellipse3);
            this.DrawingPrimitives.Add(this.m_Text8);
            this.DrawingPrimitives.Add(this.m_Text9);
            this.DrawingPrimitives.Add(this.m_Ellipse2);
            this.DrawingPrimitives.Add(this.m_Ellipse);
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_TrendViewer)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_DigitalClock)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button11)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button10)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button13)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text8)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text9)).EndInit();
        }
        
        private void m_Button11_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button11", "Click", "Show Screen", "Alarmer", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.Alarmer.Show();
        }
        
        private void m_Button10_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button10", "Click", "Show Screen", "Hjem", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.Hjem.Show();
        }
        
        private void m_Button13_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button13", "Click", "Show Screen", "Trender", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.Trender.Show();
        }
        
        private void m_Button_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button", "Click", "Show Screen", "Regulator", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.Regulator.Show();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Trender));
            this.m_Text.Text = resources.GetText("Trender.Text.Text", "Settpunkt");
            this.m_Text2.Text = resources.GetText("Trender.Text2.Text", "Prosessverdi");
            this.m_Button11.Text = resources.GetText("Trender.Button11.Text", "Alarmer");
            this.m_Button10.Text = resources.GetText("Trender.Button10.Text", "Hjem");
            this.m_Button13.Text = resources.GetText("Trender.Button13.Text", "Trender");
            this.m_Button.Text = resources.GetText("Trender.Button.Text", "Regulering");
            this.m_Text8.Text = resources.GetText("Trender.Text8.Text", "Alarm");
            this.m_Text9.Text = resources.GetText("Trender.Text9.Text", "Alarm");
            this.m_TrendViewer.Curves[0].DisplayName = resources.GetText("Trender.TrendViewer.Curves[0].DisplayName", "Curve");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_Trender) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Alarm_synling"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Text9.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Alarm_synling"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Ellipse2.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Kritisk_alarm_synling"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Ellipse.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding4 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Kritisk_alarm_synling"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Text8.DataBindings.Add(dynamicBinding4);
            this.m_DynamicBindings.Add(dynamicBinding4);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding5 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Alarm_synling"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Ellipse1.DataBindings.Add(dynamicBinding5);
            this.m_DynamicBindings.Add(dynamicBinding5);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding6 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("IsBlinkEnabled", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Kritisk_alarm_synling"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Ellipse3.DataBindings.Add(dynamicBinding6);
            this.m_DynamicBindings.Add(dynamicBinding6);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding7 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Kritisk_alarm_synling"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Ellipse3.DataBindings.Add(dynamicBinding7);
            this.m_DynamicBindings.Add(dynamicBinding7);
        }
    }
}
