//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class Trender : Neo.ApplicationFramework.Controls.Controls.Form {
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text1;
        
        private Neo.ApplicationFramework.Controls.Trend.TrendViewerCF m_TrendViewer;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button11;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button10;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button13;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text2;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text3;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle1;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle2;
        
        private Neo.ApplicationFramework.Controls.Controls.EllipseCF m_Ellipse;
        
        private Neo.ApplicationFramework.Controls.Controls.EllipseCF m_Ellipse1;
        
        private Neo.ApplicationFramework.Controls.Controls.EllipseCF m_Ellipse2;
        
        private Neo.ApplicationFramework.Controls.Controls.EllipseCF m_Ellipse3;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle9;
        
        private Neo.ApplicationFramework.Controls.Controls.DigitalClockCF m_DigitalClock;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle8;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text10;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text11;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text12;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle10;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text13;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text21;
        
        private Neo.ApplicationFramework.Controls.Controls.EllipseCF m_Ellipse4;
        
        private Neo.ApplicationFramework.Controls.Controls.EllipseCF m_Ellipse5;
        
        private Neo.ApplicationFramework.Controls.Controls.EllipseCF m_Ellipse6;
        
        private Neo.ApplicationFramework.Controls.Controls.EllipseCF m_Ellipse7;
        
        private bool m_Initialized_Trender;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf1;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf2;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf3;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf4;
        
        public Trender() {
            this.InitializeComponent();
            this.m_Button11.Click += new System.EventHandler(this.m_Button11_Action_Click);
            this.m_Button10.Click += new System.EventHandler(this.m_Button10_Action_Click);
            this.m_Button13.Click += new System.EventHandler(this.m_Button13_Action_Click);
            this.m_Button.Click += new System.EventHandler(this.m_Button_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text1);
            }
        }
        
        public Neo.ApplicationFramework.Controls.Script.TrendCFAdapterBase TrendViewer {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TrendCFAdapterBase>(this.m_TrendViewer);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button11 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button11);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button10 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button10);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button13 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button13);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Ellipse {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Ellipse);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Ellipse1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Ellipse1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Ellipse2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Ellipse2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Ellipse3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Ellipse3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle9 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle9);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter DigitalClock {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_DigitalClock);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle8 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle8);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text10 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text10);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text11 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text11);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text12 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text12);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle10 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle10);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text13 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text13);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text21 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text21);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Ellipse4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Ellipse4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Ellipse5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Ellipse5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Ellipse6 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Ellipse6);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Ellipse7 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Ellipse7);
            }
        }
        
        private void InitializeComponent() {
            this.brushdynamicsconvertercf4 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            this.brushdynamicsconvertercf3 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            this.brushdynamicsconvertercf2 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            this.brushdynamicsconvertercf1 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            Neo.ApplicationFramework.Controls.Trend.CurveCF curvecf1 = new Neo.ApplicationFramework.Controls.Trend.CurveCF();
            Neo.ApplicationFramework.Controls.Trend.CurveCF curvecf2 = new Neo.ApplicationFramework.Controls.Trend.CurveCF();
            Neo.ApplicationFramework.Controls.Trend.CurveCF curvecf3 = new Neo.ApplicationFramework.Controls.Trend.CurveCF();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval1 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval2 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF stringintervalmappercf1 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf1 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf2 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval3 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval4 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF stringintervalmappercf2 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf3 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf4 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            this.m_Text1 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_TrendViewer = new Neo.ApplicationFramework.Controls.Trend.TrendViewerCF();
            this.m_Button11 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button10 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button13 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text2 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text3 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Rectangle = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Rectangle1 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Rectangle2 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Ellipse = new Neo.ApplicationFramework.Controls.Controls.EllipseCF();
            this.m_Ellipse1 = new Neo.ApplicationFramework.Controls.Controls.EllipseCF();
            this.m_Ellipse2 = new Neo.ApplicationFramework.Controls.Controls.EllipseCF();
            this.m_Ellipse3 = new Neo.ApplicationFramework.Controls.Controls.EllipseCF();
            this.m_Rectangle9 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_DigitalClock = new Neo.ApplicationFramework.Controls.Controls.DigitalClockCF();
            this.m_Rectangle8 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Text10 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text11 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text12 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Rectangle10 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Text13 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text21 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Ellipse4 = new Neo.ApplicationFramework.Controls.Controls.EllipseCF();
            this.m_Ellipse5 = new Neo.ApplicationFramework.Controls.Controls.EllipseCF();
            this.m_Ellipse6 = new Neo.ApplicationFramework.Controls.Controls.EllipseCF();
            this.m_Ellipse7 = new Neo.ApplicationFramework.Controls.Controls.EllipseCF();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_TrendViewer)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button11)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button10)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button13)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_DigitalClock)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text10)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text11)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text12)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text13)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text21)).BeginInit();
            this.SuspendLayout();
            // 
            // Trender
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(167)))), ((int)(((byte)(167)))), ((int)(((byte)(167))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.ThreeDBorder;
            this.ControlBox = false;
            // 
            // m_Text1
            // 
            this.m_Text1.BlinkDynamicsValue = false;
            this.m_Text1.EnabledDynamicsValue = true;
            this.m_Text1.FontSizePixels = 20;
            this.m_Text1.Height = 6;
            this.m_Text1.Left = 671;
            this.m_Text1.Name = "m_Text1";
            this.m_Text1.ScreenOwnerName = "Trender";
            this.m_Text1.Top = 153;
            this.m_Text1.VisibleDynamicsValue = true;
            this.m_Text1.Width = 2;
            // 
            // m_TrendViewer
            // 
            this.m_TrendViewer.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(227)))), ((int)(((byte)(227)))), ((int)(((byte)(227))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_TrendViewer.BlinkDynamicsValue = false;
            curvecf1.BlinkDynamicsValue = false;
            curvecf1.Color = System.Drawing.Color.Red;
            curvecf1.DataSourceName = "Tags.Pådrag";
            curvecf1.DisplayName = "Curve";
            curvecf1.EnabledDynamicsValue = true;
            curvecf1.Height = 357;
            curvecf1.ScreenOwnerName = null;
            curvecf1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.Red, System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            curvecf1.VisibleDynamicsValue = true;
            curvecf1.Width = 673;
            curvecf2.BlinkDynamicsValue = false;
            curvecf2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(157)))), ((int)(((byte)(187)))), ((int)(((byte)(97)))));
            curvecf2.DataSourceName = "Tags.Settpunkt";
            curvecf2.DisplayName = "Curve1";
            curvecf2.EnabledDynamicsValue = true;
            curvecf2.Height = 357;
            curvecf2.ScreenOwnerName = null;
            curvecf2.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(157)))), ((int)(((byte)(187)))), ((int)(((byte)(97))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            curvecf2.VisibleDynamicsValue = true;
            curvecf2.Width = 673;
            curvecf3.BlinkDynamicsValue = false;
            curvecf3.Color = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(118)))), ((int)(((byte)(157)))));
            curvecf3.DataSourceName = "Tags.Prosessverdi";
            curvecf3.DisplayName = "Curve2";
            curvecf3.EnabledDynamicsValue = true;
            curvecf3.Height = 357;
            curvecf3.ScreenOwnerName = null;
            curvecf3.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(118)))), ((int)(((byte)(157))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            curvecf3.VisibleDynamicsValue = true;
            curvecf3.Width = 673;
            this.m_TrendViewer.Curves.Add(curvecf1);
            this.m_TrendViewer.Curves.Add(curvecf2);
            this.m_TrendViewer.Curves.Add(curvecf3);
            this.m_TrendViewer.EnabledDynamicsValue = true;
            this.m_TrendViewer.FontSizePixels = 11;
            this.m_TrendViewer.ForceTransparency = false;
            this.m_TrendViewer.Foreground = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_TrendViewer.GridLineColor = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_TrendViewer.Height = 434;
            this.m_TrendViewer.IndicatorMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(52D, 29.69599999999997D, 52D, 47D);
            this.m_TrendViewer.Left = 9;
            this.m_TrendViewer.Name = "m_TrendViewer";
            this.m_TrendViewer.RequiresTransparency = true;
            this.m_TrendViewer.ScaleColor = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_TrendViewer.ScreenOwnerName = "Trender";
            this.m_TrendViewer.TimeOffset = System.TimeSpan.Parse("00:00:00");
            this.m_TrendViewer.TimeRange = System.TimeSpan.Parse("00:10:00");
            this.m_TrendViewer.TimeScaleMaximum = 39083.5D;
            this.m_TrendViewer.TimeScaleMinimum = 39083.493055555555D;
            this.m_TrendViewer.TimeTextScaleMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(52D, 404D, 52D, 16.723333333333358D);
            this.m_TrendViewer.Top = 73;
            this.m_TrendViewer.Value = 0D;
            this.m_TrendViewer.ValueMajorScaleMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(32D, 29.69599999999997D, 735D, 47D);
            this.m_TrendViewer.ValueMajorScaleMaxMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(735D, 29.69599999999997D, 32D, 47D);
            this.m_TrendViewer.ValueMinorScaleMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(37D, 29.69599999999997D, 735D, 47D);
            this.m_TrendViewer.ValueMinorScaleMaxMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(735D, 29.69599999999997D, 37D, 47D);
            this.m_TrendViewer.ValueScaleMajorTickCount = 11;
            this.m_TrendViewer.ValueScaleMaximum = 100D;
            this.m_TrendViewer.ValueScaleMinimum = 0D;
            this.m_TrendViewer.ValueScaleMinorTickCount = 4;
            this.m_TrendViewer.ValueTextScaleMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(11.989999999999998D, 29.69599999999997D, 747D, 47D);
            this.m_TrendViewer.ValueTextScaleMaxMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(747D, 29.69599999999997D, 11.990000000000009D, 47D);
            this.m_TrendViewer.VisibleDynamicsValue = true;
            this.m_TrendViewer.Width = 777;
            // 
            // m_Button11
            // 
            this.m_Button11.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_Button11.BlinkDynamicsValue = false;
            this.m_Button11.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button11.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button11.EnabledDynamicsValue = true;
            this.m_Button11.FontSizePixels = 17;
            this.m_Button11.ForceTransparency = true;
            this.m_Button11.Height = 43;
            this.m_Button11.IndicatorMargin = null;
            this.m_Button11.Left = 400;
            this.m_Button11.Name = "m_Button11";
            this.m_Button11.RequiresTransparency = true;
            this.m_Button11.ScreenOwnerName = "Trender";
            this.m_Button11.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_Button11.TextHeight = 21;
            this.m_Button11.TextValue = 0D;
            this.m_Button11.TextWidth = 191;
            this.m_Button11.Top = 560;
            this.m_Button11.Value = 0D;
            this.m_Button11.VisibleDynamicsValue = true;
            this.m_Button11.VisualPropertiesHashCode = -1651545488;
            this.m_Button11.Width = 201;
            // 
            // m_Button10
            // 
            this.m_Button10.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_Button10.BlinkDynamicsValue = false;
            this.m_Button10.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button10.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button10.EnabledDynamicsValue = true;
            this.m_Button10.FontSizePixels = 17;
            this.m_Button10.ForceTransparency = true;
            this.m_Button10.Height = 43;
            this.m_Button10.IndicatorMargin = null;
            this.m_Button10.Left = -1;
            this.m_Button10.Name = "m_Button10";
            this.m_Button10.RequiresTransparency = true;
            this.m_Button10.ScreenOwnerName = "Trender";
            this.m_Button10.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_Button10.TextHeight = 21;
            this.m_Button10.TextValue = 0D;
            this.m_Button10.TextWidth = 191;
            this.m_Button10.Top = 560;
            this.m_Button10.Value = 0D;
            this.m_Button10.VisibleDynamicsValue = true;
            this.m_Button10.VisualPropertiesHashCode = -1651545488;
            this.m_Button10.Width = 201;
            // 
            // m_Button13
            // 
            this.m_Button13.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_Button13.BlinkDynamicsValue = false;
            this.m_Button13.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button13.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button13.EnabledDynamicsValue = true;
            this.m_Button13.FontSizePixels = 17;
            this.m_Button13.ForceTransparency = true;
            this.m_Button13.Height = 43;
            this.m_Button13.IndicatorMargin = null;
            this.m_Button13.Left = 599;
            this.m_Button13.Name = "m_Button13";
            this.m_Button13.RequiresTransparency = true;
            this.m_Button13.ScreenOwnerName = "Trender";
            this.m_Button13.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_Button13.TextHeight = 21;
            this.m_Button13.TextValue = 0D;
            this.m_Button13.TextWidth = 191;
            this.m_Button13.Top = 560;
            this.m_Button13.Value = 0D;
            this.m_Button13.VisibleDynamicsValue = true;
            this.m_Button13.VisualPropertiesHashCode = -1651545488;
            this.m_Button13.Width = 201;
            // 
            // m_Button
            // 
            this.m_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_Button.BlinkDynamicsValue = false;
            this.m_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button.EnabledDynamicsValue = true;
            this.m_Button.FontSizePixels = 17;
            this.m_Button.ForceTransparency = true;
            this.m_Button.Height = 43;
            this.m_Button.IndicatorMargin = null;
            this.m_Button.Left = 199;
            this.m_Button.Name = "m_Button";
            this.m_Button.RequiresTransparency = true;
            this.m_Button.ScreenOwnerName = "Trender";
            this.m_Button.SymbolIntervalMapper = symbolintervalmapper4;
            this.m_Button.TextHeight = 21;
            this.m_Button.TextValue = 0D;
            this.m_Button.TextWidth = 191;
            this.m_Button.Top = 560;
            this.m_Button.Value = 0D;
            this.m_Button.VisibleDynamicsValue = true;
            this.m_Button.VisualPropertiesHashCode = -1651545488;
            this.m_Button.Width = 201;
            // 
            // m_Text
            // 
            this.m_Text.BlinkDynamicsValue = false;
            this.m_Text.EnabledDynamicsValue = true;
            this.m_Text.FontSizePixels = 18;
            this.m_Text.Height = 21;
            this.m_Text.Left = 215;
            this.m_Text.Name = "m_Text";
            this.m_Text.ScreenOwnerName = "Trender";
            this.m_Text.Top = 515;
            this.m_Text.VisibleDynamicsValue = true;
            this.m_Text.Width = 54;
            // 
            // m_Text2
            // 
            this.m_Text2.BlinkDynamicsValue = false;
            this.m_Text2.EnabledDynamicsValue = true;
            this.m_Text2.FontSizePixels = 18;
            this.m_Text2.Height = 21;
            this.m_Text2.Left = 365;
            this.m_Text2.Name = "m_Text2";
            this.m_Text2.ScreenOwnerName = "Trender";
            this.m_Text2.Top = 515;
            this.m_Text2.VisibleDynamicsValue = true;
            this.m_Text2.Width = 68;
            // 
            // m_Text3
            // 
            this.m_Text3.BlinkDynamicsValue = false;
            this.m_Text3.EnabledDynamicsValue = true;
            this.m_Text3.FontSizePixels = 18;
            this.m_Text3.Height = 21;
            this.m_Text3.Left = 537;
            this.m_Text3.Name = "m_Text3";
            this.m_Text3.ScreenOwnerName = "Trender";
            this.m_Text3.Top = 515;
            this.m_Text3.VisibleDynamicsValue = true;
            this.m_Text3.Width = 41;
            // 
            // m_Rectangle
            // 
            this.m_Rectangle.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle.BlinkDynamicsValue = false;
            this.m_Rectangle.EnabledDynamicsValue = true;
            this.m_Rectangle.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(157)))), ((int)(((byte)(187)))), ((int)(((byte)(97))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle.Height = 21;
            this.m_Rectangle.Left = 172;
            this.m_Rectangle.Name = "m_Rectangle";
            this.m_Rectangle.ScreenOwnerName = "Trender";
            this.m_Rectangle.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle.Top = 519;
            this.m_Rectangle.VisibleDynamicsValue = true;
            this.m_Rectangle.Width = 26;
            // 
            // m_Rectangle1
            // 
            this.m_Rectangle1.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle1.BlinkDynamicsValue = false;
            this.m_Rectangle1.EnabledDynamicsValue = true;
            this.m_Rectangle1.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(130)))), ((int)(((byte)(180))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle1.Height = 21;
            this.m_Rectangle1.Left = 322;
            this.m_Rectangle1.Name = "m_Rectangle1";
            this.m_Rectangle1.ScreenOwnerName = "Trender";
            this.m_Rectangle1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle1.Top = 519;
            this.m_Rectangle1.VisibleDynamicsValue = true;
            this.m_Rectangle1.Width = 26;
            // 
            // m_Rectangle2
            // 
            this.m_Rectangle2.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle2.BlinkDynamicsValue = false;
            this.m_Rectangle2.EnabledDynamicsValue = true;
            this.m_Rectangle2.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle2.Height = 21;
            this.m_Rectangle2.Left = 493;
            this.m_Rectangle2.Name = "m_Rectangle2";
            this.m_Rectangle2.ScreenOwnerName = "Trender";
            this.m_Rectangle2.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle2.Top = 519;
            this.m_Rectangle2.VisibleDynamicsValue = true;
            this.m_Rectangle2.Width = 26;
            // 
            // m_Ellipse
            // 
            this.m_Ellipse.BlinkDynamicsValue = false;
            this.m_Ellipse.EnabledDynamicsValue = true;
            this.m_Ellipse.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse.Height = 32;
            this.m_Ellipse.Left = 426;
            this.m_Ellipse.Name = "m_Ellipse";
            this.m_Ellipse.ScreenOwnerName = "Trender";
            this.m_Ellipse.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse.Top = 565;
            this.m_Ellipse.VisibleDynamicsValue = true;
            this.m_Ellipse.Width = 33;
            // 
            // m_Ellipse1
            // 
            this.m_Ellipse1.BlinkDynamicsValue = false;
            this.m_Ellipse1.EnabledDynamicsValue = true;
            this.m_Ellipse1.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(165)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse1.Height = 32;
            this.m_Ellipse1.Left = 426;
            this.m_Ellipse1.Name = "m_Ellipse1";
            this.m_Ellipse1.ScreenOwnerName = "Trender";
            this.m_Ellipse1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse1.Top = 565;
            this.m_Ellipse1.VisibleDynamicsValue = true;
            this.m_Ellipse1.Width = 33;
            // 
            // m_Ellipse2
            // 
            this.m_Ellipse2.BlinkDynamicsValue = false;
            this.m_Ellipse2.EnabledDynamicsValue = true;
            this.m_Ellipse2.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse2.Height = 32;
            this.m_Ellipse2.Left = 426;
            this.m_Ellipse2.Name = "m_Ellipse2";
            this.m_Ellipse2.ScreenOwnerName = "Trender";
            this.m_Ellipse2.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse2.Top = 565;
            this.m_Ellipse2.VisibleDynamicsValue = true;
            this.m_Ellipse2.Width = 33;
            // 
            // m_Ellipse3
            // 
            this.m_Ellipse3.BlinkDynamicsValue = false;
            this.m_Ellipse3.EnabledDynamicsValue = true;
            this.m_Ellipse3.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(165)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse3.Height = 32;
            this.m_Ellipse3.Left = 426;
            this.m_Ellipse3.Name = "m_Ellipse3";
            this.m_Ellipse3.ScreenOwnerName = "Trender";
            this.m_Ellipse3.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse3.Top = 565;
            this.m_Ellipse3.VisibleDynamicsValue = true;
            this.m_Ellipse3.Width = 33;
            // 
            // m_Rectangle9
            // 
            this.m_Rectangle9.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle9.BlinkDynamicsValue = false;
            this.m_Rectangle9.EnabledDynamicsValue = true;
            this.m_Rectangle9.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(227)))), ((int)(((byte)(227)))), ((int)(((byte)(227))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle9.Height = 44;
            this.m_Rectangle9.Left = 531;
            this.m_Rectangle9.Name = "m_Rectangle9";
            this.m_Rectangle9.ScreenOwnerName = "Trender";
            this.m_Rectangle9.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle9.Top = 9;
            this.m_Rectangle9.VisibleDynamicsValue = true;
            this.m_Rectangle9.Width = 255;
            // 
            // m_DigitalClock
            // 
            this.m_DigitalClock.BlinkDynamicsValue = false;
            this.m_DigitalClock.DisplayFormat = Neo.ApplicationFramework.Interfaces.DateTimeDisplayFormat.DateAndTime;
            this.m_DigitalClock.EnabledDynamicsValue = true;
            this.m_DigitalClock.FontSizePixels = 20;
            this.m_DigitalClock.Height = 30;
            this.m_DigitalClock.Left = 545;
            this.m_DigitalClock.Name = "m_DigitalClock";
            this.m_DigitalClock.ScreenOwnerName = "Trender";
            this.m_DigitalClock.ShowDayOfWeek = false;
            this.m_DigitalClock.ShowSeconds = true;
            this.m_DigitalClock.Text = "04.05.2026 09:18:17";
            this.m_DigitalClock.Top = 16;
            this.m_DigitalClock.VisibleDynamicsValue = true;
            this.m_DigitalClock.Width = 205;
            // 
            // m_Rectangle8
            // 
            this.m_Rectangle8.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle8.BlinkDynamicsValue = false;
            this.m_Rectangle8.EnabledDynamicsValue = true;
            this.m_Rectangle8.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(227)))), ((int)(((byte)(227)))), ((int)(((byte)(227))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle8.Height = 44;
            this.m_Rectangle8.Left = 9;
            this.m_Rectangle8.Name = "m_Rectangle8";
            this.m_Rectangle8.ScreenOwnerName = "Trender";
            this.m_Rectangle8.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle8.Top = 9;
            this.m_Rectangle8.VisibleDynamicsValue = true;
            this.m_Rectangle8.Width = 240;
            // 
            // m_Text10
            // 
            this.m_Text10.BlinkDynamicsValue = false;
            this.m_Text10.EnabledDynamicsValue = true;
            this.m_Text10.FontSizePixels = 20;
            this.m_Text10.Height = 21;
            this.m_Text10.Left = 28;
            this.m_Text10.Name = "m_Text10";
            this.m_Text10.ScreenOwnerName = "Trender";
            this.m_Text10.Top = 16;
            this.m_Text10.VisibleDynamicsValue = true;
            this.m_Text10.Width = 37;
            // 
            // m_Text11
            // 
            this.m_Text11.BlinkDynamicsValue = false;
            brushdynamicsconvertercf1.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            brushcfinterval1.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(28)))), ((int)(((byte)(36))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval2.End = 1D;
            brushcfinterval2.Start = 1D;
            brushcfinterval2.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(177)))), ((int)(((byte)(76))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval1);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval2);
            brushdynamicsconvertercf2.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Text11.EnabledDynamicsValue = true;
            this.m_Text11.FontSizePixels = 20;
            this.m_Text11.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.m_Text11.Height = 21;
            this.m_Text11.Left = 121;
            this.m_Text11.Name = "m_Text11";
            this.m_Text11.ScreenOwnerName = "Trender";
            stringintervalmappercf1.DefaultValue = "StatusTxt";
            stringintervalcf1.End = 1D;
            stringintervalcf1.Start = 1D;
            stringintervalcf1.Value = "DRIFT";
            stringintervalcf2.Value = "INAKTIV";
            stringintervalmappercf1.Intervals.Add(stringintervalcf1);
            stringintervalmappercf1.Intervals.Add(stringintervalcf2);
            this.m_Text11.TextIntervalMapper = stringintervalmappercf1;
            this.m_Text11.Top = 16;
            this.m_Text11.VisibleDynamicsValue = true;
            this.m_Text11.Width = 49;
            // 
            // m_Text12
            // 
            this.m_Text12.BlinkDynamicsValue = false;
            brushdynamicsconvertercf3.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            brushcfinterval3.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(28)))), ((int)(((byte)(36))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval4.End = 1D;
            brushcfinterval4.Start = 1D;
            brushcfinterval4.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(177)))), ((int)(((byte)(76))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf3.BrushIntervalMapper.Intervals.Add(brushcfinterval3);
            brushdynamicsconvertercf3.BrushIntervalMapper.Intervals.Add(brushcfinterval4);
            brushdynamicsconvertercf4.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Text12.EnabledDynamicsValue = true;
            this.m_Text12.FontSizePixels = 20;
            this.m_Text12.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.m_Text12.Height = 21;
            this.m_Text12.Left = 121;
            this.m_Text12.Name = "m_Text12";
            this.m_Text12.ScreenOwnerName = "Trender";
            stringintervalmappercf2.DefaultValue = "StatusTxt";
            stringintervalcf3.End = 1D;
            stringintervalcf3.Start = 1D;
            stringintervalcf3.Value = "DRIFT";
            stringintervalcf4.Value = "STOPP";
            stringintervalmappercf2.Intervals.Add(stringintervalcf3);
            stringintervalmappercf2.Intervals.Add(stringintervalcf4);
            this.m_Text12.TextIntervalMapper = stringintervalmappercf2;
            this.m_Text12.Top = 15;
            this.m_Text12.VisibleDynamicsValue = true;
            this.m_Text12.Width = 39;
            // 
            // m_Rectangle10
            // 
            this.m_Rectangle10.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle10.BlinkDynamicsValue = false;
            this.m_Rectangle10.EnabledDynamicsValue = true;
            this.m_Rectangle10.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(227)))), ((int)(((byte)(227)))), ((int)(((byte)(227))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle10.Height = 44;
            this.m_Rectangle10.Left = 270;
            this.m_Rectangle10.Name = "m_Rectangle10";
            this.m_Rectangle10.ScreenOwnerName = "Trender";
            this.m_Rectangle10.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle10.Top = 9;
            this.m_Rectangle10.VisibleDynamicsValue = true;
            this.m_Rectangle10.Width = 240;
            // 
            // m_Text13
            // 
            this.m_Text13.BlinkDynamicsValue = false;
            this.m_Text13.EnabledDynamicsValue = true;
            this.m_Text13.FontSizePixels = 20;
            this.m_Text13.Height = 21;
            this.m_Text13.Left = 273;
            this.m_Text13.Name = "m_Text13";
            this.m_Text13.ScreenOwnerName = "Trender";
            this.m_Text13.Top = 16;
            this.m_Text13.VisibleDynamicsValue = true;
            this.m_Text13.Width = 39;
            // 
            // m_Text21
            // 
            this.m_Text21.BlinkDynamicsValue = false;
            this.m_Text21.EnabledDynamicsValue = true;
            this.m_Text21.FontSizePixels = 20;
            this.m_Text21.Height = 21;
            this.m_Text21.Left = 338;
            this.m_Text21.Name = "m_Text21";
            this.m_Text21.ScreenOwnerName = "Trender";
            this.m_Text21.Top = 16;
            this.m_Text21.VisibleDynamicsValue = true;
            this.m_Text21.Width = 42;
            // 
            // m_Ellipse4
            // 
            this.m_Ellipse4.BlinkDynamicsValue = false;
            this.m_Ellipse4.EnabledDynamicsValue = true;
            this.m_Ellipse4.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse4.Height = 32;
            this.m_Ellipse4.Left = 463;
            this.m_Ellipse4.Name = "m_Ellipse4";
            this.m_Ellipse4.ScreenOwnerName = "Trender";
            this.m_Ellipse4.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse4.Top = 15;
            this.m_Ellipse4.VisibleDynamicsValue = true;
            this.m_Ellipse4.Width = 33;
            // 
            // m_Ellipse5
            // 
            this.m_Ellipse5.BlinkDynamicsValue = false;
            this.m_Ellipse5.EnabledDynamicsValue = true;
            this.m_Ellipse5.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(165)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse5.Height = 32;
            this.m_Ellipse5.Left = 463;
            this.m_Ellipse5.Name = "m_Ellipse5";
            this.m_Ellipse5.ScreenOwnerName = "Trender";
            this.m_Ellipse5.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse5.Top = 15;
            this.m_Ellipse5.VisibleDynamicsValue = true;
            this.m_Ellipse5.Width = 33;
            // 
            // m_Ellipse6
            // 
            this.m_Ellipse6.BlinkDynamicsValue = false;
            this.m_Ellipse6.EnabledDynamicsValue = true;
            this.m_Ellipse6.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse6.Height = 32;
            this.m_Ellipse6.Left = 463;
            this.m_Ellipse6.Name = "m_Ellipse6";
            this.m_Ellipse6.ScreenOwnerName = "Trender";
            this.m_Ellipse6.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse6.Top = 15;
            this.m_Ellipse6.VisibleDynamicsValue = true;
            this.m_Ellipse6.Width = 33;
            // 
            // m_Ellipse7
            // 
            this.m_Ellipse7.BlinkDynamicsValue = false;
            this.m_Ellipse7.EnabledDynamicsValue = true;
            this.m_Ellipse7.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(165)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse7.Height = 32;
            this.m_Ellipse7.Left = 463;
            this.m_Ellipse7.Name = "m_Ellipse7";
            this.m_Ellipse7.ScreenOwnerName = "Trender";
            this.m_Ellipse7.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse7.Top = 15;
            this.m_Ellipse7.VisibleDynamicsValue = true;
            this.m_Ellipse7.Width = 33;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 600);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "Trender";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_Trender = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_Trender) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Text1);
            this.DrawingPrimitives.Add(this.m_TrendViewer);
            this.DrawingPrimitives.Add(this.m_Button11);
            this.DrawingPrimitives.Add(this.m_Button10);
            this.DrawingPrimitives.Add(this.m_Button13);
            this.DrawingPrimitives.Add(this.m_Button);
            this.DrawingPrimitives.Add(this.m_Text);
            this.DrawingPrimitives.Add(this.m_Text2);
            this.DrawingPrimitives.Add(this.m_Text3);
            this.DrawingPrimitives.Add(this.m_Rectangle);
            this.DrawingPrimitives.Add(this.m_Rectangle1);
            this.DrawingPrimitives.Add(this.m_Rectangle2);
            this.DrawingPrimitives.Add(this.m_Ellipse);
            this.DrawingPrimitives.Add(this.m_Ellipse1);
            this.DrawingPrimitives.Add(this.m_Ellipse2);
            this.DrawingPrimitives.Add(this.m_Ellipse3);
            this.DrawingPrimitives.Add(this.m_Rectangle9);
            this.DrawingPrimitives.Add(this.m_DigitalClock);
            this.DrawingPrimitives.Add(this.m_Rectangle8);
            this.DrawingPrimitives.Add(this.m_Text10);
            this.DrawingPrimitives.Add(this.m_Text11);
            this.DrawingPrimitives.Add(this.m_Text12);
            this.DrawingPrimitives.Add(this.m_Rectangle10);
            this.DrawingPrimitives.Add(this.m_Text13);
            this.DrawingPrimitives.Add(this.m_Text21);
            this.DrawingPrimitives.Add(this.m_Ellipse4);
            this.DrawingPrimitives.Add(this.m_Ellipse5);
            this.DrawingPrimitives.Add(this.m_Ellipse6);
            this.DrawingPrimitives.Add(this.m_Ellipse7);
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_TrendViewer)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button11)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button10)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button13)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_DigitalClock)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text10)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text11)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text12)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text13)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text21)).EndInit();
        }
        
        private void m_Button11_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button11", "Click", "Show Screen", "Alarmer", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.Alarmer.Show();
        }
        
        private void m_Button10_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button10", "Click", "Show Screen", "Hjem", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.Hjem.Show();
        }
        
        private void m_Button13_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button13", "Click", "Show Screen", "Trender", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.Trender.Show();
        }
        
        private void m_Button_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button", "Click", "Show Screen", "Regulator", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.Regulator.Show();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Trender));
            this.m_Button11.Text = resources.GetText("Trender.Button11.Text", "Alarmer");
            this.m_Button10.Text = resources.GetText("Trender.Button10.Text", "Hjem");
            this.m_Button13.Text = resources.GetText("Trender.Button13.Text", "Trender");
            this.m_Button.Text = resources.GetText("Trender.Button.Text", "Regulering");
            this.m_Text.Text = resources.GetText("Trender.Text.Text", "Settpunkt");
            this.m_Text2.Text = resources.GetText("Trender.Text2.Text", "Prosessverdi");
            this.m_Text3.Text = resources.GetText("Trender.Text3.Text", "Pådrag");
            this.m_TrendViewer.Curves[0].DisplayName = resources.GetText("Trender.TrendViewer.Curves[0].DisplayName", "Curve");
            this.m_TrendViewer.Curves[1].DisplayName = resources.GetText("Trender.TrendViewer.Curves[1].DisplayName", "Curve1");
            this.m_TrendViewer.Curves[2].DisplayName = resources.GetText("Trender.TrendViewer.Curves[2].DisplayName", "Curve2");
            this.m_Text10.Text = resources.GetText("Trender.Text10.Text", "Status");
            this.m_Text11.Text = resources.GetText("Trender.Text11.Text", "StatusTxt");
            this.m_Text12.Text = resources.GetText("Trender.Text12.Text", "StatusTxt");
            this.m_Text13.Text = resources.GetText("Trender.Text13.Text", "Alarm:");
            this.m_Text21.Text = resources.GetText("Trender.Text21.Text", "Normal");
            resources.ApplyTexts(this.m_Text11, "Texts", "Trender.Text11.Texts[0]", "DRIFT", "Trender.Text11.Texts[1]", "INAKTIV");
            resources.ApplyTexts(this.m_Text12, "Texts", "Trender.Text12.Texts[0]", "DRIFT", "Trender.Text12.Texts[1]", "STOPP");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_Trender) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Alarm_tekst"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Text21.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("IsBlinkEnabled", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Alarm_kritisk_høy"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Ellipse4.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Alarm_kritisk_høy"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Ellipse4.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding4 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("BorderBrush", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.StatusTxt"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf3);
            this.m_Text12.DataBindings.Add(dynamicBinding4);
            this.m_DynamicBindings.Add(dynamicBinding4);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding5 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Background", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.StatusTxt"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf4);
            this.m_Text12.DataBindings.Add(dynamicBinding5);
            this.m_DynamicBindings.Add(dynamicBinding5);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding6 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.StatusTxt"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueZero);
            this.m_Text12.DataBindings.Add(dynamicBinding6);
            this.m_DynamicBindings.Add(dynamicBinding6);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding7 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Alarm_kritisk_lav"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Ellipse6.DataBindings.Add(dynamicBinding7);
            this.m_DynamicBindings.Add(dynamicBinding7);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding8 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("IsBlinkEnabled", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Alarm_lav"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Ellipse7.DataBindings.Add(dynamicBinding8);
            this.m_DynamicBindings.Add(dynamicBinding8);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding9 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Alarm_lav"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Ellipse7.DataBindings.Add(dynamicBinding9);
            this.m_DynamicBindings.Add(dynamicBinding9);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding10 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("IsBlinkEnabled", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Alarm_høy"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Ellipse5.DataBindings.Add(dynamicBinding10);
            this.m_DynamicBindings.Add(dynamicBinding10);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding11 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Alarm_høy"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Ellipse5.DataBindings.Add(dynamicBinding11);
            this.m_DynamicBindings.Add(dynamicBinding11);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding12 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("IsBlinkEnabled", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Alarm_kritisk_lav"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Ellipse6.DataBindings.Add(dynamicBinding12);
            this.m_DynamicBindings.Add(dynamicBinding12);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding13 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.StatusTxt"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Text12.DataBindings.Add(dynamicBinding13);
            this.m_DynamicBindings.Add(dynamicBinding13);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding14 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Alarm_høy"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Ellipse1.DataBindings.Add(dynamicBinding14);
            this.m_DynamicBindings.Add(dynamicBinding14);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding15 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("IsBlinkEnabled", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Alarm_kritisk_lav"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Ellipse2.DataBindings.Add(dynamicBinding15);
            this.m_DynamicBindings.Add(dynamicBinding15);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding16 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Alarm_kritisk_lav"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Ellipse2.DataBindings.Add(dynamicBinding16);
            this.m_DynamicBindings.Add(dynamicBinding16);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding17 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("IsBlinkEnabled", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Alarm_kritisk_høy"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Ellipse.DataBindings.Add(dynamicBinding17);
            this.m_DynamicBindings.Add(dynamicBinding17);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding18 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Alarm_kritisk_høy"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Ellipse.DataBindings.Add(dynamicBinding18);
            this.m_DynamicBindings.Add(dynamicBinding18);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding19 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("IsBlinkEnabled", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Alarm_høy"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Ellipse1.DataBindings.Add(dynamicBinding19);
            this.m_DynamicBindings.Add(dynamicBinding19);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding20 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("BorderBrush", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.StatusTxt"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf1);
            this.m_Text11.DataBindings.Add(dynamicBinding20);
            this.m_DynamicBindings.Add(dynamicBinding20);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding21 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Background", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.StatusTxt"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf2);
            this.m_Text11.DataBindings.Add(dynamicBinding21);
            this.m_DynamicBindings.Add(dynamicBinding21);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding22 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.StatusTxt"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Text11.DataBindings.Add(dynamicBinding22);
            this.m_DynamicBindings.Add(dynamicBinding22);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding23 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("IsBlinkEnabled", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Alarm_lav"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Ellipse3.DataBindings.Add(dynamicBinding23);
            this.m_DynamicBindings.Add(dynamicBinding23);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding24 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Alarm_lav"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Ellipse3.DataBindings.Add(dynamicBinding24);
            this.m_DynamicBindings.Add(dynamicBinding24);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding25 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.StatusTxt"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Text11.DataBindings.Add(dynamicBinding25);
            this.m_DynamicBindings.Add(dynamicBinding25);
        }
    }
}
